### ISSUE TITLE
enable clearing UPNs from UserInfo entries stored in Azure Storage

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#1014]
Story: I need to remove all email addresses after 30 days.

We need to support a scheduled task that removes UPNs from `UserInfo` structs in the Azure Storage Tables after some duration.  

As of this issue, these are Job, Task, and Repo structs need to have UPNs scrubbed. 

AB#39994473

**Comment by mgreisen** [comment]
Resolved with PR #1051
