### ISSUE TITLE
Machines in scaleset are stuck in init state

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#1021]
## Information

- Onefuzz version: 2.23.0
- OS: Windows latest

## Provide detailed reproduction steps (if any)

Submitted our integration test job but it appears to be stuck.

```
onefuzz jobs get 6d23b847-eefa-473c-a258-63c32f6afe64 --query 'task_info[].state'
[
    "waiting",
    "waiting",
    "scheduled"
]
```

Check relevant scalesets -- we use 1 machine from this one, which should be fine since 1 is free.

```
onefuzz scalesets get b14e93a1-8fd1-4400-9933-b02ad70b342e --query nodes
[
    {
        "instance_id": "5",
        "machine_id": "b6890749-f2b8-4833-8d12-e6c765e2f3e3",
        "state": "done"
    },
    {
        "instance_id": "6",
        "machine_id": "bd22631e-be2f-475a-9926-22737f2daeb2",
        "state": "free"
    }
]
```

But this one seems to be in a weird state:

```
onefuzz scalesets get 0efe1fc6-441f-4501-b9e1-5945b1528a56 --query nodes
[
    {
        "instance_id": "0",
        "machine_id": "51424bf9-4edf-43bc-92a4-e9546d61a93f",
        "state": "init"
    },
    {
        "instance_id": "1",
        "machine_id": "d9c25725-6bf0-4178-aabc-7ef1e200e348",
        "state": "init"
    }
]
```

I believe this instance was upgraded to 2.23.0 recently, so not sure if it's related to the upgrade or not.

### Expected result

Machines to be in free state

### Actual result

Machines appear to be stuck in init state. Checked `traces` logs and didn't see anything obvious. There's some scaleset issues in the `exceptions` logs, possibly related?

**Comment by jagunter** [comment]
Ran `onefuzz nodes reimage 51424bf9-4edf-43bc-92a4-e9546d61a93f` but node is still showing as reimage not requested.

```
{
    "debug_keep_node": false,
    "delete_requested": false,
    "machine_id": "d9c25725-6bf0-4178-aabc-7ef1e200e348",
    "messages": [],
    "pool_name": "***",
    "reimage_requested": false,
    "scaleset_id": "0efe1fc6-441f-4501-b9e1-5945b1528a56",
    "state": "init",
    "tasks": [],
    "version": "2.23.0"
}
```

**Comment by bmc-msft** [comment]
The scaleset exception logs are related.
