### ISSUE TITLE
Crash report generation task failed with NOTIFICATION_FAILURE

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#1022]
## Information

- Onefuzz version: 2.23.0
- OS: Windows latest

## Provide detailed reproduction steps (if any)

Our custom task which creates crash reports for ADO was stopped. 

```
    "heartbeat": "2021-06-25T02:47:24+00:00",
    "job_id": "74935610-a9a1-49f8-81b5-c90e8ddb073a",
    "nodes": [],
    "os": "windows",
    "state": "stopped",
    "task_id": "362e6303-bd0c-4a6f-83c6-4c1ad6ea859f"
```

The error associated with the task:

```
"error": {
        "code": 470,
        "errors": [
            "notification failed",
            "TF401349: An unexpected error has occurred, please verify your request and try again."
        ]
    },
```

The error appears to be related to creating a work item in ADO: https://developercommunity.visualstudio.com/t/tf401349-an-unexpected-error-has-occurred-when-upd/442958

### Expected result

Is it expected notification failures will fail the report generation task?

### Actual result

Task failed

**Comment by jagunter** [comment]
Double checked and the PAT used to create this work item has not yet expired.

**Comment by bmc-msft** [comment]
It is expected that notification failures fail the reporting task.

**Comment by jagunter** [comment]
On 2.23.1 got a more detailed failure message:

```
    "error": {
        "code": 470,
        "errors": [
            "notification failed",
            "TF26071: This work item has been changed by someone else since you opened it.  You will need to refresh it and discard your changes."
        ]
    },
```
