### ISSUE TITLE
Setting `target_options` in `libfuzzer basic` breaks `libfuzzer_regression` task

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1039]
### Versions

OneFuzz: 2.23.1

First reported on Windows, also repro'd on Linux.

### Repro 
Create a `libfuzzer basic` job with a present `target_options` arg, like:
```
onefuzz template libfuzzer basic --target_exe fuzzer.exe --target_options=-max_len=4096
```

Instead of running like normal, the `libfuzzer-regression` task fails immediately with an error like:
```
error running task: evaluating argument failed: {input} Caused by: missing argument {input}
```
This also fails the job's `libfuzzer_crash_report` task (the rest continue running).

**Comment by chkeita** [comment]
fixed by #1066
