### ISSUE TITLE
Managed nodes stuck in init on Windows after finishing task

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#1041]
## Information

- Onefuzz version: 2.23.1 (node), 2.24.0 (instance)
- OS: Windows latest

## Provide detailed reproduction steps (if any)

A job recently finished on a set of machines. However, it looks like these machines are now stuck in the `init` state. Example:

```
{
    "debug_keep_node": false,
    "delete_requested": false,
    "machine_id": "b61b12a4-cc36-4e43-be1b-a04d399f8f61",
    "messages": [
        {
            "stop_if_free": {}
        }
    ],
    "pool_name": "***",
    "reimage_requested": true,
    "scaleset_id": "1339d1c1-5d28-4481-8de0-d25eaec5a188",
    "state": "init",
    "tasks": [],
    "version": "2.23.1"
}
```

It may be worth noting that the OneFuzz instance has been upgraded to 2.24.0 while the job was running.

### Expected result

Node to eventually move to the `free` state so that tasks in the pool queue can be picked up.

### Actual result

Node is stuck in the `init` state. The last message I can find in `traces` with this machine id in the `customDimensions` has a timestamp of `2021-06-24T03:31:59.074Z`. The message contains the output from one of our tasks, confirming it was at some point actively running a job.

**Comment by jagunter** [comment]
Forgot about #1021, looks to be the same symptoms though those machines were on 2.23.0.

**Comment by jagunter** [comment]
Another machine that appears to be stuck in init after running a task.

```
{
    "debug_keep_node": false,
    "delete_requested": false,
    "machine_id": "b6890749-f2b8-4833-8d12-e6c765e2f3e3",
    "messages": [],
    "pool_name": "***",
    "reimage_requested": false,
    "scaleset_id": "b14e93a1-8fd1-4400-9933-b02ad70b342e",
    "state": "init",
    "tasks": [],
    "version": "2.24.0"
}
```

**Comment by bmc-msft** [comment]
PR #1060 and #1059 address two issues that could lead to this case.
