### ISSUE TITLE
More tasks than expected with custom job launching script

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#1058]
## Information

- Onefuzz version: 2.24.0 - 2.25.1
- OS: Windows

## Provide detailed reproduction steps (if any)

When running our custom launcher script to launch our jobs, we've noticed more tasks than what we requested. Example jobs exhibiting the issue:

* `56947214-b5ff-48ef-9c36-eaddb90f5dc8` -- 1 more task than expected. OneFuzz version 2.25.1. No task errors.
* `c830c7a2-9054-4459-979e-e8ea51b2d597` -- 1 more task than expected (different task than above). OneFuzz version 2.25.1. One of the duplicate tasks reported an error while running.
* `287e028d-859d-403f-bf89-dfc8f4a7d3c7`  -- 2 more tasks than expected. Both duplicate tasks have the same config and differ from above. This was on OneFuzz 2.24.0. Several tasks had error `"task never started"`

Can provide script command and logs of script output on request.

### Expected result

Requested number of tasks

### Actual result

More than requested number of tasks.

**Comment by bmc-msft** [comment]
On creating one of the tasks, it the request at the SDK times out (but from the service, completes). 
   The request retry code resubmits the task creation.
