### ISSUE TITLE
Configurable disk size

### ISSUE THREAD

**Issue by tunz** [microsoft/onefuzz#112]
Seems like the disk size for fuzzing (`/onefuzz`) is fixed. (by OS image?)

Even if we change the vm size, the temporary storage is attached to other drive such as `F:\` in Windows or `/mnt` in Linux. 
```
onefuzz@node000009:/onefuzz$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           797M  708K  796M   1% /run
/dev/sda1        29G  3.6G   26G  13% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda15      105M  3.6M  101M   4% /boot/efi
/dev/sdb1        74G   53M   70G   1% /mnt
tmpfs           797M     0  797M   0% /run/user/998
tmpfs           797M     0  797M   0% /run/user/1000
```

#8 might be a solution. I'm not sure if there's an easier way to achieve this. 

AB#39994760

**Comment by bmc-msft** [comment]
The in-progress effort to support non-azure VMs for fuzzing will enable the work required to resolve #8.  Once #8 is resolved, it should be straight forward to enable configurable working directories for Azure VM nodes (such as `F:\` or `/mnt` as this issue indicated).

**Comment by tunz** [comment]
not sure. we needed this feature to move to onefuzz. but, we ended up using our own infra, and we don't have any plan to move to onefuzz in the near future afaik.

**Comment by stishkin** [comment]
Out of scope for near future
