### ISSUE TITLE
ExpressRoute Compatibility w/ OneFuzz - Proxy & Virtual Network Refactor Work

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#1159]
In order to make OneFuzz compatible with ExpressRoute, a brief refactor will need to be applied to the current VMSS/Proxy/Virtual Network architecture. 
Namely, the below changes need to be made: 
- The VMSS Virtual Network (ex. westus2) needs to be changed from 10.0.0.0/8 to a subnet that does not conflict with ExpressRoute. We could make this value configurable at runtime. 
- The proxy's networking components need to be partitioned onto it's own virtual network (ex. proxy-network). This will allow us to link ExpressRoute and it's virtual gateway to **only** the proxy. This network will need to be peered to the VMSS vNet. 
- Make the proxy-network subnet(s) configurable at deployment time. Any OneFuzz instance onboarded to ExpressRoute will need to have a unique subnet for the proxy with the proxy-network. In addition, the proxy-network must have a configurable 'Gateway Subnet.' The subnet range must also be unique.

* [x] #1280

**Comment by ranweiler** [comment]
This had one task item, which is now complete. Do we need to split out some more? @nharper285
