### ISSUE TITLE
Go language support

### ISSUE THREAD

**Issue by giorgiozoppi** [microsoft/onefuzz#118]
We have a huge code base using Go, we would like to know if we can use this tool or what changes are required to support Go.

**Comment by bmc-msft** [comment]
Earlier today, I added a [OneFuzz sample using Golang](https://github.com/microsoft/onefuzz-samples/tree/main/examples/golang) built using [go-fuzz](https://github.com/dvyukov/go-fuzz)'s libfuzzer mode.

Targets built using go-fuzz in libfuzzer mode work for fuzzing in OneFuzz without modification with the following caveats: 
1. While crashes from go-fuzz targets are recorded appropriately in OneFuzz, crash reports are not.  OneFuzz does not appropriately generate crash reports for libfuzzer crashes that don't use ASAN_LOG.  (Issue #122 )
2. As go-fuzz does not use [sancov](http://clang.llvm.org/docs/SanitizerCoverage.html) for coverage, OneFuzz is unable to track coverage growth of your fuzzing jobs.  (Issue #123 )

**Comment by bmc-msft** [comment]
Supporting coverage for non-sancov instrumented binaries is under active development but is a larger feature beyond supporting golang.

Once issue #122 is addressed, we will consider golang support to be supported as a first-class feature and I will resolve this issue.

**Comment by inferno-chromium** [comment]
Just fyi, check out https://github.com/mdempsky/go114-fuzz-build that uses native instrumentation and is available from Go 1.14 [we switched from dyvukov go-fuzz-build to this in oss-fuzz some months back].

**Comment by bmc-msft** [comment]
I'll check that in the morning. Thanks for the pointer!
