### ISSUE TITLE
OneFuzz CLI command to download current CLI version from endpoint service

### ISSUE THREAD

**Issue by MichaelSquires** [microsoft/onefuzz#1197]
I'd like to be able to download the OneFuzz CLI version that matches my endpoint service without having to interact with pip (have a python installation available, pip install onefuzz, query the endpoint, pip install onefuzz the reported version). 

@bmc-msft suggested a CLI command that could download the correct version from the endpoint. I'm inferring this would mean a version-agnostic command where any (reasonably recent - e.g. within the same major version) CLI could query the endpoint and download a version of the CLI that matches the version the endpoint is running. 

This feature would enable automated scripts (such as pipelines) to be able to easily download the correct CLI version from the endpoint and then submit jobs without needing a python installation. Additionally, the download should be a lot faster than the pip method and save a lot of pipeline job time. 

AB#35971

**Comment by ranweiler** [comment]
This seems reasonable and useful for teams, and would make instances a bit more "self-service".

Thinking out loud about implementation / acceptance criteria:
1. I think we'd probably want to keep copies of the latest CLI (for both Windows/Linux) in a new blob storage container in the non-user data `func...` storage account.
2. We'd update that new container at deploy time, and we'd want to ensure that normal OneFuzz CLI / API commands cannot access that container.
3. We'd probably implement this via a new API endpoint and CLI sub-command like `onefuzz cli get` or `onefuzz cli download_latest`.

**Comment by MichaelSquires** [comment]
Whatever sub-command you decide on, can you also add an option to specify the output file? Something like `-o <outfile>`? I'd like to be able to use an older client to connect and download the correct version client and then call the new client without having to also figure out what version it is. Example cmd/ps1 script:
```
onefuzz-cli-2.18.0.exe config ...
onefuzz-cli-2.18.0.exe cli get -o onefuzz-cli.exe

onefuzz-cli.exe template libfuzzer ...
```

(Also thinking out loud here:) If allowed by policy, another idea might be to save needing an existing client in the first place by having a non-auth URL where I can always download the latest CLI. That way, I can just download the correct version CLI from the endpoint using something like curl or Invoke-WebRequest:
```
curl -Lo onefuzz-cli.exe https://<endpoint>/cli/latest/windows
onefuzz-cli.exe template libfuzzer ...
```

**Comment by bmc-msft** [comment]
> (Also thinking out loud here:) If allowed by policy, another idea might be to save needing an existing client in the first place by having a non-auth URL where I can always download the latest CLI. 

Unfortunately, this is harder to do in an authenticated fashion.

**Comment by mgreisen** [comment]
Closing.
