### ISSUE TITLE
Visualizing custom metrics from Application Insights when access to OneFuzz instance is restricted

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#1210]
The OneFuzz instance we're operating on allows a broad class of users to submit jobs to OneFuzz, but only certain users with additional credentials have direct access to the Azure resources. As a result, a user that submits a fuzzer to OneFuzz may not have access to traces and metrics in Application Insights. As a work-around, service principals have been created for users that need that access. So far this has worked okay.

Now we're experimenting with allowing users to submit custom traces and metrics to the OneFuzz Application Insights instance using the `instance_telemetry_key`. This gives us better control of the severity level in our traces for filtering, and allows us to better capture internal fuzzer statistics. Trace and metrics can be queried in their raw form using the service principal via `onefuzz debug logs query`.

For the custom metrics, we're interested in users being able to visualize them in some fashion. I was considering Power BI but am open to additional suggestions here. Some limitations with the current state:

* Service principals can't be used to authenticate to Application Insights through Power BI.
* Power BI requires the query to be written in a different format (M-Query). There is a conversion routine in Azure that can transform a log query into an M-Query, but this requires access to Application Insights. https://docs.microsoft.com/en-us/azure/azure-monitor/app/export-power-bi#export-an-analytics-query

Opening this issue to gather thoughts on best ways to support visualization of custom metrics. The goal is to allow users to easily visualize their custom metrics. 

AB#39994238

**Comment by stishkin** [comment]
this can be achieved using Azure managed Grafana dashboards, and use Kusto language to run queries
