### ISSUE TITLE
deploy.py script calls register_application() even if the application exists

### ISSUE THREAD

**Issue by andrew-slutsky** [microsoft/onefuzz#1225]
## Information

- Onefuzz version: all
- OS: all

The deploy.py script calls register_application() even though the 'onefuzz-cli' app exists in the current tenant. This results in the creation of a new secret each time you invoke deploy.py if you are the Owner of the 'onefuzz-cli' in your tenant. The result is that now our 'onefuzz-cli' App Registration has hundreds, soon to be thousands of unused secrets, see the image below.

## Provide detailed reproduction steps (if any)

Create a new OneFuzz instance on any tenant other than Microsoft, e.g. a personal Azure subscription or the PME tenant.

The resulting behavior is different if you are the Owner or not of the 'onefuzz-cli' app on your tenant, even though the script succeeds in both cases. Which is pretty strange.

This issue is caused by the fact that the ONEFUZZ_CLI_APP is hard coded to the Microsoft tenant. It should be changed so that if the user provides a client_id as a command line argument then script should use that app ID instead of the global variable when applying the filter (sorry, I did not test this solution):

OLD CODE:
cli_app = list(client.applications.list(filter="appId eq '%s'" % ONEFUZZ_CLI_APP))
        
NEW CODE:
cli_app = list(client.applications.list(filter="appId eq '%s'" % self.cli_config["client_id"]))

In my opinion, if you create a new instance using deploy.py, it should create a new app registration "onefuzz-cli-INSTANCE_NAME", instead of attempting to reuse a single one per tenant. It would be a simpler model and users will understand things clearly.

There are a couple different issue at hand here and it's not my intention to muddy the water. I just suggest they're all handled at the same time. If you have any questions please feel free to reach out over Teams directly. 

SECRETS:

![image](https://user-images.githubusercontent.com/73055543/132067851-da1fcd1c-ddf2-4430-8150-4e770c4357ea.png)

(it goes on for several pages) 

AB#39994232

**Comment by chkeita** [comment]
There are two concerns in this issue
- The deployment scripts add a new password entry on each deployment. 
    - This is addressed in the PR #966 - The new code limits the number of passwords for an application to two
- The deployment script ignores the `client_id` parameter. A new PR will be created to handle that issue

**Comment by chkeita** [comment]
The last outstanding issue has been addressed in #2305
