### ISSUE TITLE
Terminate fuzzers before node teardown

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#1227]
Currently on completion of the fuzz job, the `supervisor_exe` in `generic_supervisor`  is not terminated before teardown begins. This can cause the fuzzer to believe there are e.g. file system failures and start recording errors that are ultimately benign. This creates noise for our integration tests, which check for errors in the logs from our fuzzer and flag if any are present. 

AB#39994224

**Comment by chkeita** [comment]
addressed in #1444
