### ISSUE TITLE
Add 'Deployer' as owner of Function App Managed Identity (Enterprise App) during deployment

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#1251]
In order to stay compliant with certain Microsoft directives, we must regulate app permissions and authentication settings. Many of these configuration are done at the function app managed identity-level (or enterprise application). This identity is created indirectly during deployment and, consequently, is not created with an actual 'owner' who can manage the settings of the principal. 

I'm requesting that we research how to add the 'deployer' of the instance in question as an owner of this enterprise application/managed identity. 

AB#39994210

**Comment by mgreisen** [comment]
We have not control over the ownership. Closing.
