### ISSUE TITLE
Increase default level of feedback/confirmation in destructive commands 

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1264]
Some CLI commands invoke requests to endpoints that don't return rich descriptions of executed actions. As a result, the CLI can be confusingly quiet, even when significant or destructive actions have been carried out.

An example from a user:

1. For the jobs that do not have associated containers, running `onefuzz jobs containers delete <job-id>` doesn't output anything. It would help to e.g. render a JSON object that makes it clear that nothing was done (intentionally and successfully).
	
2. For the above command, the `--dryrun` flag does not indicate whether the containers have already been deleted. It could be useful if it did. This may require tracking more container metadata, or making additional queries.

**Comment by stishkin** [comment]
Opened separate bug to track (2)  of the bug: #1282
