### ISSUE TITLE
move to using async appinsights

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#1266]
When we first started using `appinsights-rs`, only a blocking mode was available.

With the 0.2 release, an async version is available.  Moving to the async model rather than a separate thread would be beneficial from a maintenance stance. 

AB#39994197

**Comment by ranweiler** [comment]
Two questions to consider:
1. Do we currently emit telemetry from any code that is non-async? We might have internal library code that is not itself async, and emits telemetry (even though we always used in an async application).
2. Do we anticipate needing to be able to?

The answers to each is probably "no", but at a minimum, (1) is a possible refactoring gotcha to be aware of.

**Comment by chkeita** [comment]
@Porges i think you looked at this in #2033 and #2091

**Comment by Porges** [comment]
Both the blocking and non-blocking implementations seem to have a problem, at least with the way we are using it. I wasn't able to get a clean `check-pr` run with either. Will require more investigation.
