### ISSUE TITLE
Deployment fails in westus3 due to "Region doesn’t support Classic resource mode for Application Insights resources."

### ISSUE THREAD

**Issue by stishkin** [microsoft/onefuzz#1273]
## Information

- Onefuzz version:3.0.0
- OS:N/A

## Provide detailed reproduction steps (if any)

1. Download latest OneFuzz `deploy` artifact
2. Run `deploy.py` using `westus3` region 

### Expected result

_What is the expected result of the above steps?_
Deployment succeeds

### Actual result

_What is the actual result of the above steps?_
Deployment Fails
```json
Exception Details:      (BadRequest) {
          "code": "BadRequest",
          "message": "Region doesn’t support Classic resource mode for Application Insights resources. Please use Workspace-based mode.",
          "innererror": {
            "diagnosticcontext": "88b2a52a-abd3-4eeb-8e6e-041f11df37f0",
            "time": "2021-09-23T19:33:43.7541640Z"
          }
        }
        Code: BadRequest
        Message: {
          "code": "BadRequest",
          "message": "Region doesn’t support Classic resource mode for Application Insights resources. Please use Workspace-based mode.",
          "innererror": {
            "diagnosticcontext": "88b2a52a-abd3-4eeb-8e6e-041f11df37f0",
            "time": "2021-09-23T19:33:43.7541640Z"
          }
        }
```

**Comment by bmc-msft** [comment]
https://github.com/microsoft/onefuzz/blob/7da4352e275835a18d097de544adc1166fd18f9f/src/deployment/deploy.py#L202

**Comment by stishkin** [comment]
Steps for fixing the issue:
- Fix validation to make sure that all resources are available in the region
- Port existing app-insights to newer version
