### ISSUE TITLE
How to analyze code coverage for libfuzzer

### ISSUE THREAD

**Issue by stmh-infosec** [microsoft/onefuzz#1288]
Hey Team,

I have been following https://github.com/microsoft/onefuzz/blob/main/docs/how-to/understand-libfuzzer-coverage.md to understand code coverage of my target application. I am bit new to understanding code coverage, could you please let me know how to open and understand .cov files. Should I have to use llvm-cov or any other tools to understand this data ? Also, do I have to compile my binary with -fprofile-instr-generate -fcoverage-mapping to generate better coverage results ?

**Comment by ranweiler** [comment]
@stmh-infosec, sorry, these docs are actually now out of date! I've add #1289 and self-assigned to fix that.

You should now use the `coverage` (_not_ `libfuzzer_coverage`) task, which is also what our CLI job "templates" now default to. The reports from this task do not require any tooling to interpret. The new task leverages (but does not require) Sancov instrumentation if available, but cannot leverage the profiling instrumentation flags you asked about (you should omit them).

The old `.cov` files were a raw dump of the fuzzer's Sancov 8-bit counter/bool-flag table, which is different from (and less useful than) the `.sancov` format compatible with LLVM's Sancov utilities.

The new `coverage` task generates a JSON description of coverage, which is basically self-explanatory. See [here](https://github.com/microsoft/onefuzz/blob/main/src/agent/coverage/src/block.rs#L534-L559). As I mentioned, the new task's coverage recording is Sancov-aware, and will use 8-bit counter, bool-flag, or PC table instrumentation to maximize coverage precision, depending on what is detected in the target exe.

**Comment by stmh-infosec** [comment]
@ranweiler , thanks for the detailed response, I will check out the latest release :).
