### ISSUE TITLE
Remove compat shim for scaleset identities

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1293]
In 1.6.0, we started using a [user-assigned identity](https://github.com/microsoft/onefuzz/blob/main/CHANGELOG.md#changed-36) for scalesets.

To ease upgrades, we have back-compat shim code in `endpoint_authorization`, [here](https://github.com/microsoft/onefuzz/blob/22b2d62e2959d02d4e7a4b411315549d5be592e3/src/api-service/__app__/onefuzzlib/endpoint_authorization.py#L27-L31).

We are now 2 major versions past when we introduced the shim, and should remove it on the next breaking release. 

AB#35965

**Comment by chkeita** [comment]
code removed when converting the service to C#
