### ISSUE TITLE
Remove compat shims for `SecretData`

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1294]
In 2.0, we introduced [Azure KeyVault management](https://github.com/microsoft/onefuzz/blob/main/CHANGELOG.md#changed-30) of secrets for notification templates.

In doing so, we added the `SecretData` class, and shim validators to the template models:
- [`ADOTemplate`](https://github.com/microsoft/onefuzz/blob/22b2d62e2959d02d4e7a4b411315549d5be592e3/src/pytypes/onefuzztypes/models.py#L263)
- [`TeamsTemplate`](https://github.com/microsoft/onefuzz/blob/22b2d62e2959d02d4e7a4b411315549d5be592e3/src/pytypes/onefuzztypes/models.py#L279)
- [`GithubIssueTemplate`](https://github.com/microsoft/onefuzz/blob/22b2d62e2959d02d4e7a4b411315549d5be592e3/src/pytypes/onefuzztypes/models.py#L475)

We should remove this shim logic in a future breaking release, and further simplify `SecretData` if possible. 

[AB#35877](https://fuzzfest.visualstudio.com/Onefuzz/_workitems/edit/35877)

**Comment by chkeita** [comment]
The compatibity was meant to convert from the format specified in our [contribs](https://github.com/microsoft/onefuzz/blob/main/contrib/onefuzz-job-github-actions/github-issues.json). We will need to update these examples too
