### ISSUE TITLE
Microsoft.Web/serverFarms fails to deploy (specific subscription/specific region)

### ISSUE THREAD

**Issue by stishkin** [microsoft/onefuzz#1298]
## Information

- Onefuzz version: N/A
- OS: N/A

## Provide detailed reproduction steps (if any)
There are some subscriptions that fail to deploy Microsoft.Web/serverFarms resource with "Frobidden" runtime error.

### Expected result

_What is the expected result of the above steps?_
Report an error to the user, and suggestion to select a different region to deploy due to `serverFarms` not supported in the specified region. OneFuzz deployment should fail preferably before starting Azure deployment.

### Actual result

_What is the actual result of the above steps?_
OneFuzz deployment proceeds and gets stuck. In Azure portal in `Deployments` tab one can see following failure:
![image](https://user-images.githubusercontent.com/7307755/135175841-d9505701-9ca1-4fa6-b562-8d6014c8448a.png)
 

AB#39994160

**Comment by ranweiler** [comment]
@stishkin, can we assign this to you?

**Comment by stishkin** [comment]
@ranweiler  Assigned to myself
