### ISSUE TITLE
Revisit docs

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1339]
We have many docs, but they are inconsistent in level of detail, and are not organized into an approachable, navigable whole.

Let's revisit this, and ensure we have a curated, extremely useful set of user-focused docs. When possible, leverage existing docs for our recommended fuzzing tools (e.g. libFuzzer). Distinguish between the user scenarios of (1) instance admin, (2) non-specialist template-focused users, (3) users who will leverage customized tasks and the SDK. 

AB#35963

**Comment by Porges** [comment]
Closing this as nebulous. We have had some specific targeted improvements to docs recently.
