### ISSUE TITLE
Invalid config with `job_templates` in `features` can't be updated via CLI

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1345]
## Information

- Onefuzz version: 3.1.0
- OS: Windows 10 (observed)

## Provide detailed reproduction steps (if any)

1. Create a CLI `config.json` with some _invalid_ `endpoint`/`authority`/`client_id`. A genuinely nonexistent `endpoint` URL is sufficient.
2. Add the value `"job_templates"` to the `features` list of `config.json`.  `templates.json` can be nonexistent.
3. Try to use `onefuzz config` to point to a validate instance, e.g. using the `deploy.py` instructions

### Expected result

`config.json` should get set to the valid instance specified in the `onefuzz config` args. If prompted to authenticate, auth should be attempted using the _new_ args passed in `onefuzz config`. IOW, the `onefuzz config` args should be merged over the local `config.json`, and only _then_ should any remote calls be attempted.

### Actual result

The local `config.json` is never updated, and the old/existing (in this case: invalid) endpoint params are used for the attempt at authenticating. When the endpoint is invalid (or the user is not authorized for the endpoint), this will always fail, and it will be impossible to update the `config.json` using the CLI.

### Workaround

Manually remove `"job_templates"` from `features` in `config.json`, or delete the `config.json` entirel. _Then_ attempt `onefuzz config`. 

AB#35962

**Comment by mgreisen** [comment]
@nharper285 this will be addressed with your PR that addresses https://github.com/microsoft/onefuzz/issues/2774 please close this issue when you merge the PR.
