### ISSUE TITLE
Upgrade `time` and `chrono` crates

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1366]
The `chrono` and `time` crates share a possible segfault related to thread-unsafe use of `getenv()` and `setenv()`.

- [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159.html): potential segfault in `time`
- [RUSTSEC-2020-0071](https://rustsec.org/advisories/RUSTSEC-2020-0071.html): potential segfault in `chrono`

Ensure these are both fixed upstream.

Note: a patch is available for `time`, which we depend on via `chrono` (it suffers twice from the same API usage error). However, `chrono` itself does not yet have a public patch. 

AB#39994083

**Comment by chkeita** [comment]
a fix is planned for the release 4.2.0 of chrono https://github.com/chronotope/chrono/issues/674

**Comment by djc** [comment]
FYI, chrono 0.4.20 has now been released.

**Comment by Porges** [comment]
We still need `appinsights-rs` to update. I’ve sent them a PR here: https://github.com/dmolokanov/appinsights-rs/pull/280

Once this is merged we should be able to update.
