### ISSUE TITLE
Need more documentation and HOW TO with fuzzing templates such as Radamsa

### ISSUE THREAD

**Issue by stmh-infosec** [microsoft/onefuzz#1390]
I have been using the libfuzzer template for a while now on onefuzz. I wanted to try other templates like radamsa. I have been trying to use the trivial-crash sample(https://github.com/microsoft/onefuzz-samples/tree/main/examples/trivial-crash). I did compile fuzz.c with gcc rather than clang and the command i used is `gcc fuzz.c -fsanitize=address,undefined -o fuzz.exe` . I have used the below as my starter script to try in on my local ubuntu system.
`counter=1
while true
do
	radamsa "./seeds/pass.txt" > fuzz.txt
	echo "Processing test case: $counter"
	counter=$[$counter+1]
	./fuzz.exe fuzz.txt > /dev/null
	test $? -eq 1 && echo "Crashed..." && cp fuzz.txt fuzz_$counter.txt #&& break

done
`
While this works great on my local system, porting it to use radamsa template has been difficult. I tried the below two commands to schedule jobs, neither of them worked.

- `onefuzz template radamsa basic --target_exe fuzz.exe --inputs ./seeds/ radamsa_fuzzexe test 1.0 radamsa-linux --generator_exe ./radamsa_script.sh` (it still points to generic_generator)
- `onefuzz template radamsa basic --target_exe fuzz.exe --inputs ./seeds/ radamsa_fuzzexe test 1.0 radamsa-linux`

Any documentation around usage of templates with sample apps would be helpful. In this case, any guidance would be helpful.

Update: I have also looked into how the crashes could be triaged, eg: some error codes are (echo $?) 127,139 and 134, which could be easily triaged as crashed on local system using the above mentioned bash script, but how do I port the same logic to onefuzz and mainly what is the existing logic of onefuzz radamsa in triaging crashes when fuzzing with radamsa.

**Comment by ranweiler** [comment]
@stmh-infosec, agreed, adding tutorial docs is on our to-do list!

The second command you shared **should** have successfully created a job (you're on the right track). I just double-checked on a 3.2.0 instance. The job and tasks get created, and crashes are found. If you still can't launch a job that makes it to the `running` state, or it fails unexpectedly, please open a bug report (following the issue template for bugs).

In the absence of more docs: first, check out the template code [here](https://github.com/microsoft/onefuzz/blob/main/src/cli/onefuzz/templates/radamsa.py#L120-L140). Note the `generator_exe` and `generator_options` args. These define the `generator_exe` used, and how to invoke it to _generate a batch of test cases_ (in a temporary directory, on the VM). Each test case is then _tested against the `target_exe`_. Importantly, if you don't set `target_options`, we default to [setting it to `{input}`](https://github.com/microsoft/onefuzz/blob/main/src/cli/onefuzz/templates/radamsa.py#L34). If you specify your own `target_options`, we try to check that you didn't omit `{input}` in your args.

Our templates are truly just scripts that use the OneFuzz SDK and some helper functions (but baked into the CLI). The `radamsa basic` template creates, among other tasks, a `generic_generator` task, assuming a (shipped-by-default) copy of `radamsa`. The `generate_exe` parameter is thus, in this template, set to `radamsa`, and the args being used are controlled by `generator_options`. The core fuzzing loop of `generic_generator` is very similar to your start script (see [here](https://github.com/microsoft/onefuzz/blob/main/src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs#L112-L121)). Hopefully this helps a bit with how to think about that task (and the `radamsa basic` template).

**Comment by stmh-infosec** [comment]
Thanks for the detailed information, this has been very helpful.
