### ISSUE TITLE
Fuzzer no longer works due to missing GLIB_2.32 on Ubuntu host

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#1445]
## Information

- Onefuzz version: 3.2.0
- OS: Linux
- Image: "Canonical:UbuntuServer:18.04-LTS:latest"

## Provide detailed reproduction steps (if any)

Build executable with Rust compiler:

```
rustc 1.56.0-nightly (50171c310 2021-09-01)
```

Error when running, job id: `ce427366-a44b-47d2-8965-07ceaa2115d5`:

```
/lib/x86_64-linux-gnu/libc.so.6: version ``GLIBC_2.32' not found (required by /onefuzz/blob-containers/fuzzpremium01/fuzzer )
```

### Expected result

Fuzzer to run

### Actual result

Fuzzer crashes. Did something change recently on these hosts, like host configuration or something? Fuzzer was built with Rust, haven't updated in some time. Was working previously. Sample job id from last month: `89674587-9b51-4e1c-a74b-559054e24d0b`

**Comment by ranweiler** [comment]
@jagunter, if the fuzzer links against that version of glibc, I would genuinely expect it not to work on 18.04 (and _never_ to have worked). Will follow up offline about where the fuzzer is built, and where it has previously been successfully scheduled.

**Comment by ranweiler** [comment]
Resolved offline: the build environment was updated, which genuinely changed the minimum glibc version to one that is too new for 18.04.
