### ISSUE TITLE
Documentation on troubleshoot fuzzing jobs on VM scalesets

### ISSUE THREAD

**Issue by stmh-infosec** [microsoft/onefuzz#1448]
Following the guidance here(https://github.com/microsoft/onefuzz/issues/1235), I scheduled a fuzzing job using the cli(`onefuzz template radamsa ...`). My setup folder has been successfully uploaded, but I am not sure if the setup.ps1 has been respected in terms of installation. Also, I wish to know if the scale-set instances have been running into issues. My instances are windows instances and I have been trying to login to those using Azure bastion, I looked into the the code(https://github.com/microsoft/onefuzz/pull/620) where-in I see that the username and passwords have been setup for windows instances. I have checked the key-vault to look for keys/password but didn't find any. 

Is there an option to troubleshoot these instances ? Where is the password for the windows instances stored ? What would be the ideal/recommended way to troubleshoot these scenarios ? Any recommendations of these would be helpful.

**Comment by chkeita** [comment]
In general the debugging functionality of OneFuzz can be found under the `onefuzz debug command`.
you can remote to the machine running a task with `onefuzz debug task [rdp|ssh] <tak_id>` or  to a specific node in scaleset with `onefuzz debug scalesets [rdp|ssh] <scaleset_id> <node_id>`

**Comment by stmh-infosec** [comment]
Thank you!! Will give it a try :) .
