### ISSUE TITLE
Feature request for AFL variants on Windows platform 

### ISSUE THREAD

**Issue by stmh-infosec** [microsoft/onefuzz#1457]
I have looked at the feature requests and noticed that AFL++ was requested and has been implemented. 

Are there plans to support WinAFL or any closed source binary instrumented fuzzing tools for windows binaries/executables ?

**Comment by ranweiler** [comment]
> Are there plans to support WinAFL or any closed source binary instrumented fuzzing tools for windows binaries/executables ?

These are already supported, via our larger support for custom fuzzers. To quote an [earlier answer](https://github.com/microsoft/onefuzz/issues/3#issuecomment-695059517) to the issue requesting AFL++:

> User-provided custom fuzzers is a first-class supported feature. We have a few examples, including honggfuzz, domato, and even compiling an libfuzzer targets from oss-fuzz integrated projects.

Even the CLI's current `afl basic` template lets you override the `afl-fuzz` binary via uploading an alternative to an arbitrary blob storage container in your OneFuzz instance, then setting [`--supervisor_exe`](https://github.com/microsoft/onefuzz/blob/main/src/cli/onefuzz/templates/afl.py#L34) and [`--afl_container`](https://github.com/microsoft/onefuzz/blob/main/src/cli/onefuzz/templates/afl.py#L50). For AFL-like fuzzers, which spawn and monitor a target child process, you will typically want to orchestrate fuzzing with `generic_supervisor` as the fuzzer task, your custom fuzzer as the `supervisor_exe`, and your program under test as the `target_exe`. Please consult the existing use of that task in the AFL template.

We may ship additional fuzzers by _default_ in the future, but there are no immediate plans to do so.
