### ISSUE TITLE
Parse Azure Resource IDs into models

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1464]
In `onefuzz.azure.image`, for example, we use `msrestazure.tools.parse_resource_id()` to get a `dict` representation of the components of an Azure Resource ID. This is _very_ dynamic and weakly-typed, and prone to absent keys in some situations, as a result of the `parse_resource_id()` function's return type and API.

Instead of doing ad hoc, implicit recognition of what kind of resource we are parsing, we should have models for the resource types we know about, grouped in a `Union`. 

See comment: https://github.com/microsoft/onefuzz/pull/1450/files#r751810404 

[AB#35946](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/35946)

**Comment by Porges** [comment]
Won't address this for Python version but have updated the C# version to understand better the resource types that it is handling.

**Comment by Porges** [comment]
Decided to make it a "proper" discriminated union after all, since that allows much earlier validation.

**Comment by mgreisen** [comment]
@Porges has this been addressed then?

**Comment by Porges** [comment]
> @Porges has this been addressed then?

Yes, will close when PR merges.
