### ISSUE TITLE
Guidance on using custom user defined crash dump directory and custom command like options 

### ISSUE THREAD

**Issue by stmh-infosec** [microsoft/onefuzz#1478]
_Custom user defined crash dump directory:_
I have been trying to leverage radamsa on windows instance. The application that I am trying to fuzz using radamsa uses a custom folder to log dumps when a crash occurs. I wish to know if there is any specific flag that could be leveraged to overwrite the default crash folder. I took a look at (https://github.com/microsoft/onefuzz/blob/aa745501606f7c65c08349166e2d9e15fdda7879/src/agent/onefuzz-agent/src/local/generic_generator.rs#L111, https://github.com/microsoft/onefuzz/blob/aa745501606f7c65c08349166e2d9e15fdda7879/src/agent/onefuzz-agent/src/local/generic_analysis.rs#L95) and https://github.com/microsoft/onefuzz/blob/main/docs/command-replacements.md where its mentioned that `{crashes}` will be replaced at run time. Could you help me understand the workflow of input generation, crash-getting triggered and the generic_analyzer getting invoked. (_Background: I have fuzzed 2 apps, one with custom crash dump location and other following default directory, onefuzz identifies crashes with app with default directory for crash dumps and no crashes for custom location, so my other question is that is it the crash dump that triggers the generic_analyzer ? _).

_custom command like options:_
How would someone onboard an application which accepts multiple inputs as part of command like options. I do understand that we have `--target-options` and `--target-env`, but how could I structure my command which has multiple `sample inputs` consuming parameters. eg: `target_exe.exe -o input_1.img -d input_2.sh` , here input_1.img is my `sample inputs` that wish to pass as `--inputs` and `input_2.sh` would be static file that would be provided as part of `--setup_dir`.  My question is, how would I leverage `--target-options` to structure my command with inputs from `--inputs`.

**Comment by stmh-infosec** [comment]
Also, is there an option to slowdown the execution (wait time option) with `generic_generator` (I see radamsa generating inputs and then the target_exe is invoked to consume the inputs) ? The crash dumps are getting generated in `C:\Windows\Temp` directory, but are remaining as .tmp files instead of .dmp as they are getting overwritten on each execution. (Background: I have been trying to fuzz MSWord, Notepad kind of application which opens the file as a UI which consumes time)

**Comment by chkeita** [comment]
> I wish to know if there is any specific flag that could be leveraged to overwrite the default crash folder

There is currently no way to change the crash folder

> I took a look at (...)

The code you are referenced is not being used when fuzzing in the cloud. That code is meant for fuzzing locally which is currently an undocumented feature.

> Could you help me understand the workflow of input generation, crash-getting triggered and the generic_analyzer getting invoked

You are using the radamsa template. You can see how the tasks are being linked to each other in [radamsa.py](https://github.com/microsoft/onefuzz/blob/main/src/cli/onefuzz/templates/radamsa.py). 
The template creates a job with 3 tasks 
```
fuzzer -+---------->  crash_report
             |
             |
             +---------->  analyzer
```
The `fuzzer task` outputs the crash results into the `crash` container. Every crash triggers a `crash report` and an `analysis` from their respective tasks. 
The fuzzer itself works by generating multiple inputs with radamsa. Then the target is run on every inputs. If a crash occurs, the input is written to the crash container.

> How would someone onboard an application which accepts multiple inputs as part of command like options

using the list of [variable substitutions](https://github.com/microsoft/onefuzz/blob/main/docs/command-replacements.md) you can use the following command line for your use case 
`target_exe.exe -o {input} -d {setup_dir}/input_2.sh`


> Also, is there an option to slowdown the execution (wait time option) with generic_generator

No, the wait time between the generation of the input and running the application is not configurable. 
However, the timeout for running the application is configurable via the `target_timeout`. Unfortunately, we do not expose that value currently in the `radamsa` template (will be addressed in #1491).

**Comment by stmh-infosec** [comment]
Thanks @chkeita for the details. 

_There is currently no way to change the crash folder_ : 
Is there a specific crash container directory that I could point my application to ? My understanding is that the crash container directory is being monitored for changes and whenever the. directory is updated, the `crash report` and `analysis` get triggered. If I know the directory its monitoring, I could make my application  point to that directly using the registry keys. Is it the arbitrary `C:\<<uniq container name>>\onefuzz\crashes` directory ?  along with the `ready_only_inputs` directory ?

_No, the wait time between the generation of the input and running the application is not configurable.
However, the timeout for running the application is configurable via the target_timeout. Unfortunately, we do not expose that value currently in the radamsa template (will be addressed in #1491)._

Does this mean, with this option I get to control the target_exe termination time ? That would definitely help in creating a proper dump file. Also do I have to make sure that the dump file has a unique name everytime it crashes ? or is it the being taken care by the `crash_report` or `analyzer` tasks ?

**Comment by chkeita** [comment]
> Is there a specific crash container directory that I could point my application to ?

No the application only received the input file as a parameter.  You could get the directory from the path but this not a supported scenario, there is no guarantee that we will keep the same directory. 

> My understanding is that the crash container directory is being monitored for changes and whenever the. directory is updated, the crash report and analysis get triggered.

There seems to be a misconception here. The fuzzer, the analysis and the report task run on 3 **logically distinct** machines. 
So when a crash is created by the fuzzer the file gets uploaded to the container then downloaded by the other tasks. 
I assume you are using the analysis task to create your custom dump. In that case the target application does not have accsess to the original crash folder. 
If your application generates something special. you can create script that launches your application then grab all the files needed and put them in the `output_dir` of the analysis_task.


> Does this mean, with this option I get to control the target_exe termination time
Yes the `target_timeout` is the amount of time we wait to consider the application unresponsive

**Comment by stmh-infosec** [comment]
_The fuzzer, the analysis and the report task run on 3 logically distinct machines._: Got it!!
_So when a crash is created by the fuzzer the file gets uploaded to the container then downloaded by the other tasks._: How does a crash get created by the fuzzer in this case ? I mean supervisor/agent.exe is running radamsa.exe and is generating mutations based on the `--inputs` and the mutated files are being created under `C:\Windows\Temp`. Then these files are being fed to `--target-exe`. My understanding is that the radamsa.exe is a fire-and-forget tool which doesn't keep a tab on crashes. My question is when the `target_exe` is fed with the input which would generate a crash, which component identifies that a crash has occurred and how does it do that ? Is it based on evenlog or a minidump file getting created or any custom logic ? (Background: My application is generating crashes, but I am not able to see that in crash directory and the onefuzz status option)

**Comment by chkeita** [comment]
I should have written this
> when a crash **is detected** by the fuzzer **the input file** that caused the crash is uploaded
We then repeat the process

So what ends up in the crash container is the **only** input file that caused a crash. Radamsa **generates** the input files then we detect if the that input cause a crash. This is done by running the target under [a debugger](https://github.com/microsoft/onefuzz/blob/332ede42efc2be8b50f4f8084e9e345e6fd7558b/src/agent/input-tester/src/tester.rs#L126).
