### ISSUE TITLE
Issue with upgrading onefuzz to latest version

### ISSUE THREAD

**Issue by stmh-infosec** [microsoft/onefuzz#1561]
I having been working on upgrading onefuzz instances to latest versions 2.16 -> 4.0.0. During the deployment, I have been getting the below error: 

```
Exception Details:	(BadRequest) {
	  "error": {
	    "code": "RoleAssignmentUpdateNotPermitted",
	    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
	  }
	}
	Code: BadRequest
	Message: {
	  "error": {
	    "code": "RoleAssignmentUpdateNotPermitted",
	    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
	  }
	}

```
I looked at the known issues and tried removing all non existing service principals from the resource group by navigating to the resource group > Access Control (IAM) > Role Assignments and removing all entries marked as "Identity not found". **I still face the same issue. The deployment breaks with the above error** 

Is there any other way that I could get over this error and get my deployment successful ? The above deletion was done through the Azure portal and I assume it lists all the non existing service principals, is there a way to validate it with az cli ?

**Comment by chkeita** [comment]
There seems to be a conflict in the role assignment of your resources. 
Using the same steps you followed before,  you can try removing all role assignment with the scope `This resource` and redeploy

**Comment by stmh-infosec** [comment]
@chkeita , does it mean there were some role assignment changes when compared between 2.16.0 and 4.0.0 ? Do I need to manually remove those roles between the cli and the onefuzz app and then re-deploy instead of --upgrade ?

Also, I have a separate with the 4.0.0 version and we have been getting the below warning message. I remember that this is just a logging message. Is there are way to get rid of this ?

`WARNING:nsv-backend:failed to get access token with scope api://****.azurewebsites.net/.default`

**Comment by chkeita** [comment]
> @chkeita , does it mean there were some role assignment changes when compared between 2.16.0 and 4.0.0 ? 

It is hard to say, we only added new role assignments so they should not cause any conflict.

> Do I need to manually remove those roles between the cli and the onefuzz app and then re-deploy instead of --upgrade ?

The role only applies to the resource group that should be the only place you need to remove them. And yes, a full redeploy is preferable

> Also, I have a separate with the 4.0.0 version and we have been getting the below warning message.

It seems your app registration for the 4.0.0 was not upgraded. You can try to delete it then redeploy, this should recreate it without using your data

**Comment by stmh-infosec** [comment]
Hey @chkeita , thanks for the response. 

> It is hard to say, we only added new role assignments so they should not cause any conflict.

Do you think this readme(https://github.com/microsoft/onefuzz/blob/main/docs/AADEntitites.md) is updated with the new role assignment information or the changes ? The reason for asking is that in corporate environments, creation of apps and assignment of roles through deployment script becomes tedious and we have to do it manually. So if any information on new role assignments could be great so that we could configure those manually and point our deployment script to use the existing apps. We had been using `--upgrade` option till date, but looks like 4.0.0 might require a re-do.

> It seems your app registration for the 4.0.0 was not upgraded. You can try to delete it then redeploy, this should recreate it without using your data

Would there be any difference in app registrations from the code prospective ? I assume, it would have to be the service principals, app roles and api permission changes right ? We are also seeing that with 4.0.0 (different upgrade deployment), scan jobs are getting invoked through cli, but they never get into `running` state. They are either in `waiting` or `scheduled` state.

**Comment by stmh-infosec** [comment]
So, I went back and was trying to troubleshoot. When we try to do a upgrade from 2.31.0 to 4.0.0 using the --upgrade option OR using the existing `client_id` and `client_secret` of the registered server app (instance name), the deployment goes well (succeeds) as it doesn't touch the rbac flow anymore, but when jobs are scheduled the jobs are in waiting and scheduled state and never go into running state. I have also see that they stop immediately.

So, I went ahead and did the entire deployment (not using the `client_id` and `client_secret` or the --upgrade) and my deployment fails at https://github.com/microsoft/onefuzz/blob/main/src/deployment/deploy.py#L618 as I don't have enough privileges to perform role assignments. Could you help me understand if the `assign_user_access()` is required for the application to run ? Where does it have its impact ? 

Also, I see that `assign_user_access()` is assigning my `user_id` to the role and the server app(instance name). If I had to use a service principal to perform the deployment, would this still work ? Also, I am trying to have a service principal oriented automated deployment, any pointers on how to do it ? I tried leveraging the apps service principal and it fails during deployment when it tries to do `get_application` with the graph query (https://github.com/microsoft/onefuzz/blob/main/src/deployment/deploy.py#L376)

This(https://github.com/microsoft/onefuzz/blob/main/docs/AADEntitites.md#onefuzz-application-registration and https://github.com/microsoft/onefuzz/blob/main/docs/AADEntitites.md#managed-node-service-principal) documentation wiki needs to be updated to reflect the requirements for latest version that is the `UserAssignment` roles and the assignment of the user to the role.

**Comment by chkeita** [comment]
> Could you help me understand if the assign_user_access() is required for the application to run ? Where does it have its impact ?

`assign_user_access()` is there to ensure that the service principal used in the deployment has access to the instance. This is necessary because the default  in 4.0.0 is to only allow access to users that are authorized in the application. 
So you could skip it as long as you either disable `Assignment required` on the service principal of your application registration deployment or manually add a user to it. 

> This(https://github.com/microsoft/onefuzz/blob/main/docs/AADEntitites.md#onefuzz-application-registration and https://github.com/microsoft/onefuzz/blob/main/docs/AADEntitites.md#managed-node-service-principal) documentation wiki needs to be updated to reflect the requirements for latest version that is the UserAssignment roles and the assignment of the user to the role.

@nharper285 can you update the doc to reflect the changes introduced by `assign_user_access()`

**Comment by stmh-infosec** [comment]
> So you could skip it as long as you either disable Assignment required on the service principal of your application registration deployment or manually add a user to it.

Just double confirming, this is for the deployment access right ? not the onefuzz-cli command line access of the users from their terminal correct ? (because that happens through the secret creation on the `onefuzz-cli` application)

**Comment by nharper285** [comment]
Updated docs wrapped into PR https://github.com/microsoft/onefuzz/issues/1581

**Comment by stmh-infosec** [comment]
Thanks, the above PR makes it clear now.
