### ISSUE TITLE
OneFuzz job state for different tasks remain in scheduled or waiting states with Onefuzz version 4.0.0

### ISSUE THREAD

**Issue by nageshn66** [microsoft/onefuzz#1570]
Launching a onefuzz job the tasks will never comeout of waiting and scheduling states. Checking on different containers shows empty list.

## Information

- Onefuzz version: 4.0.0
- OS: Linux ubuntu

## Provide detailed reproduction steps (if any)

1.
2.
3.

### Expected result

To see state as completed an see the crash reports

### Actual result

empty list

**Comment by ranweiler** [comment]
Hello! This is not enough information. Please share repro steps, as requested in the issue template. These should include the commands you invoked (redacted as appropriate) to create the pool, scaleset(s), and the jobs you expect to run on those compute resources.

**Comment by nageshn66** [comment]
Here are the steps I followed after a successful onefuzz deployment.
**Steps:**

- onefuzz config --endpoint https://app-d-adsk-onefuzz-dev.azurewebsites.net --authority https://login.microsoftonline.com/67bff79e-7f91-4433-a8e5-c9252d2ddc1d --client_id 268f7285-2b35-4433-9a22-e55d91ed118f --client_secret xxxx
- onefuzz pools create nagesh-linux-pool1 linux
- onefuzz scalesets create nagesh-linux-pool1 4
- Built a sample libfuzzer job target fuzz.exe and copied this file to current folder
- onefuzz template libfuzzer basic --target_exe fuzz.exe --inputs onefuzz-samples/examples/simple-libfuzzer/seeds libfuzzer-samplefuzz-program1 sample-fuzz-proj1 1.0 nagesh-linux-pool1
- job gets successfull created with jobId
- Querying job details, will see all tasks created and the state being in Waiting or Scheduled state.
- From here, it will never come to complete or finished.
- So, never get to see any crash report.

**Comment by ranweiler** [comment]
Thank you, @nageshn66!

What are the `state` values for the responses to:
1. `onefuzz pools get nagesh-linux-pool1`
2. `onefuzz scalesets get <id-of-your-scaleset>`

Do you have any Trace log events in your Application Insights resource with severity level of `Error`?

**Comment by ranweiler** [comment]
@nageshn66, please don't share the raw output of the CLI commands here. I have removed your comment because it contained a [SAS URL](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview). You should delete your pool and recreate it.

I did see what I needed, which was the `state` field (only) of the pool and scaleset nodes, so thank you.

**Comment by ranweiler** [comment]
Please investigate the answer to this question:

> Do you have any Trace log events in your Application Insights resource with severity level of Error?

**Comment by nageshn66** [comment]
HI @ranweiler, I found the issue with this. I was using wrong service principal in my script which was scoped for a different resource group. Now, I'm able to launch the fuzz job and view the results, no more sitting in scheduled and waiting states.

**Comment by ranweiler** [comment]
Closing due to successful resolution on the user's end.
