### ISSUE TITLE
Update Default Linux Images to Ubuntu 20.04

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#1590]
In April 2022, Ubuntu will release 22.04 LTS. This means that all of the proxy and default linux scalesets we create will be two LTS version behind. 

Filing this item to start a conversation about upgrading our default images to 20.04.  

AB#39993951

**Comment by mgreisen** [comment]
1. Create a new workitem regarding the proxy change
2. Update this work item with the detail around what is needed to include the image specific data for pools and scalesets.

**Comment by Porges** [comment]
It might be good to get #2790 done first to make the agent more independent

**Comment by Porges** [comment]
This is complete.
