### ISSUE TITLE
7-Day Scaleset Re-Image Also Upgrades Nodes

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#1592]
So currently OneFuzz reimages nodes after 7 days (this is a feature I requested a while back). That codepath just reimages the nodes, which is not necessarily the same as upgrading them. It might be worth looking into expanding that functionality to also call the 'upgrade' feature.

**Comment by mgreisen** [comment]
Noah will investigate

**Comment by nharper285** [comment]
Work completed in PR #1612. Closing Work item.
