### ISSUE TITLE
Radamsa fuzzing in windows- task generic_crash_report

### ISSUE THREAD

**Issue by prasanthbalaji** [microsoft/onefuzz#1600]
## Information

- Onefuzz version: 4.0.0
- OS:Windows 10

## Provide detailed reproduction steps (if any)

input directory contains files which causes crashes. (manually tested)
1. onefuzz template redamsa basic  --setup_dir <<>> --target_exe <<>> --inputs <<>>  --target_timeout <<>> --reboot_after_setup --duration 72 <<project>> <<name>> <<buildid>>  <<pool name>>
2. onefuzz debug task rdp <<generic_analysis taskid>>
3.

### Expected result

generic_crash_report in running state
with crashes

### Actual result

generic_crash_report in running state
no crashes found.

**Comment by prasanthbalaji** [comment]
onefuzz debug task rdp <<generic_analysis taskid>>   Event viewer shows authentication error shown below.

![image](https://user-images.githubusercontent.com/6666424/150615653-0fec784f-ad7b-436e-b038-1b1105ec452f.png)

**Comment by chkeita** [comment]
@prasanthbalaji can you provide more details about your jobs. how many machine are in your pool. 
Also you can check the Appinsight logs to see if any error were generated during the run

**Comment by prasanthbalaji** [comment]
There are 4 windows machines in the pool. I did not see any other error in onfuzz.log, onefuzz-run.log and onefuzz-setup.log (above mentioned parameter notfound error in this file)

**Comment by chkeita** [comment]
No the logs i am refering to are the logs the App insight instance on the server. Not the machine. Make sure to search in the window of time when you created your job

**Comment by prasanthbalaji** [comment]
which log should I look into . 
![image](https://user-images.githubusercontent.com/6666424/150874439-c0d8fbe8-a275-4e10-85d1-4fca7bb34a43.png)

**Comment by chkeita** [comment]
Try the transaction search. 
You can search for your job id in the top bar. This should give you an overview of the logs since the jobs has been scheduled
![image](https://user-images.githubusercontent.com/244326/150875101-94dfe91f-c948-4ccd-9b5c-f3ac5282e3a6.png)

**Comment by prasanthbalaji** [comment]
![image](https://user-images.githubusercontent.com/6666424/150877313-59f782f9-285b-4245-ac43-884ef9b57e45.png)

**Comment by chkeita** [comment]
can you run 
`onefuzz status stop` to see the state of the fuzzing 
can you also confirm which binaries you are using ?

**Comment by prasanthbalaji** [comment]
![image](https://user-images.githubusercontent.com/6666424/150880315-d75fc236-c4d6-4b19-af7e-9f8e1a68f195.png)

**Comment by chkeita** [comment]
If the pool where you launched your job has at least one node, there is no obvious reason the report task was not scheduled. 
We will need to drill down in the logs of that task so see where it stopped processing. 
in the appinsight can you search for the task id and see the last couple of messages related to that task. 
i am trying to get an idea of the current state of the task  in the service.

**Comment by prasanthbalaji** [comment]
I could not find logs for  taskid :4b4d0a6a.
But I could find logs for 392ea61f..
![Screenshot_1_24_22__3_40_PM](https://user-images.githubusercontent.com/6666424/150883983-9be1e99a-b624-4788-8ea7-971f56a137f2.png)

**Comment by chkeita** [comment]
You need to search closer to the time when the job was created. You opened the bug 3 days ago so the 4 hours filter will not be enough to cover what we need.

**Comment by prasanthbalaji** [comment]
I submitted this job today again within 4hr rage.

**Comment by chkeita** [comment]
Can you try increasing the number of machine in your scaleset to at least 5
The radamsa template is configured to run 
- 2 machine for the fuzzer
- 2 machines for analysis 
- 1 machine for the crash report. 

So it is possible that in a pool of just 4 machines the crash report task never gets run.

**Comment by prasanthbalaji** [comment]
It has been more than 18hrs still don't see any crashes. 
![image](https://user-images.githubusercontent.com/6666424/151078205-21fd960c-7e93-4825-b956-42a30dd52c10.png)

**Comment by chkeita** [comment]
Are all your task running now?
IT seems like the fuzzing task is not finding any crashes. Have you validated outside of onefuzz that you can produce crashes when using radamsa on your taget with your seeds ?
You can search for the string  "Generating test cases with"  which is [emitted](https://github.com/microsoft/onefuzz/blob/2ad37bdfb0be0be372940b676861b7320837b082/src/agent/onefuzz-agent/src/tasks/fuzz/generator.rs#L203) when we generated test cases. This will tell us if we are running the generator but cannot detect a crash

**Comment by prasanthbalaji** [comment]
Yes all 3 tasks are still running.
![image](https://user-images.githubusercontent.com/6666424/151214355-b35707f9-8e07-4bcb-81c7-9b0a38abf60c.png)

I have validated seed input files causes crashes manually.
I see the  "Generating test cases with" in the search logs
![image](https://user-images.githubusercontent.com/6666424/151214762-9109b05b-0938-4965-aff4-885657706cec.png)

**Comment by prasanthbalaji** [comment]
I was not able to find the exact temp folder  when I RDPed into the generator task. But I could find a different folder name (.tmpuu...) in which I found the input files generated by radamsa(also looks like tempfolder gets renamed and refreshed often). I manually ran the command and I could see the critical error detected.
![Screenshot_CDB_Command](https://user-images.githubusercontent.com/6666424/151224879-c478b9aa-4e0c-4ec1-876b-42212a4badad.png)
Screenshot of the exception. 
![image](https://user-images.githubusercontent.com/6666424/151224950-4b1dac97-a442-4376-afb6-4d3aa36e6252.png)

**Comment by prasanthbalaji** [comment]
I get a "no new candidate input found, sleeping"

![image](https://user-images.githubusercontent.com/6666424/151304812-f990672f-96a4-4be9-b843-c98d696e8abc.png)


When I looked into the code generic.rs, this message is thrown when the the queue is empty.

![image](https://user-images.githubusercontent.com/6666424/151304899-d406f97f-4328-4b24-b4a3-9ff53f891651.png)

**Comment by prasanthbalaji** [comment]
radamsa generated inputs rapidly twice and after that I never saw this in the logs

![image](https://user-images.githubusercontent.com/6666424/151305721-20df5cdf-4a53-4de4-84e8-075ac58cbb3f.png)

**Comment by chkeita** [comment]
Seems like there is an issue when testing  the output. 
can you filter the trace by severity and show only errors and warnings 
![image](https://user-images.githubusercontent.com/244326/151412740-ee948316-b9b5-4fd7-8043-8b2ae0d3c9d9.png)

**Comment by chkeita** [comment]
We can also try to increase the verbosity of your logs.

For that, in your `func*****` storage account, container `tools`  you will need to edit the blob `win64/onfuzz.ps1` and set the log level to `trace`.  Then redeploy your scale set. 
![image](https://user-images.githubusercontent.com/244326/151420494-79a89503-6e46-49e0-a303-2e96726c6e36.png)

Note that this change will affect all windows machines in your instance. So, make sure to revert it when you are done with the investigation

**Comment by prasanthbalaji** [comment]
I was able to update onefuzz.ps1 file and created the scaleset. We are able to see the trace logs screen shots provided below. In the screen shot we are able to see the "Generating test cases with command" as well as "testing input", but nothing after that indicating that the debug code has identified the crash. We also looked into the code (tester.rs)to see any additional strings to indicate a crash.

![image](https://user-images.githubusercontent.com/6666424/151455086-bdfded68-00a7-4ad3-82ce-7b3928e1e1b2.png)

```
pub fn test_application(&self, input_path: impl AsRef<Path>) -> Result<InputTestResult> {
        let app_args = args_with_input_file_applied(&self.driver_args, &input_path)?;

        let mut module_cache = self
            .module_cache
            .write()
            .map_err(|err| anyhow::format_err!("{:?}", err))?;

        crash_detector::test_process(
            &self.driver,
            &app_args,
            &self.driver_env,
            Duration::from_secs(self.max_run_s),
            self.ignore_first_chance_exceptions,
            Some(&mut *module_cache),
        )
        .and_then(|result| {
            let result = InputTestResult::new(result, PathBuf::from(input_path.as_ref()));
            log_input_test_result(&result);
            Ok(result)
        })
    }
 

```

**Comment by prasanthbalaji** [comment]
BTW, I could not connect to generator via `onefuzz debug task rdp `RDP. It happens to me randomly.

**Comment by prasanthbalaji** [comment]
Hey @chkeita , do we have a local build for the agent(generator, test_application) that we could debug. Looks like the debugger is not able to identify the crash. I have used simple `winappdbg` scripts to run it locally to validate that it does identify when the exception happens, I want to see if we can add debugs statements to the agent and run it locally.

Looks like the agent is passing the test file and the target exe to is_crash and later to `test_input` (https://github.com/microsoft/onefuzz/blob/main/src/agent/onefuzz/src/input_tester.rs#L294-L391) which ultimately ends up in `test_input_debugger` (https://github.com/microsoft/onefuzz/blob/main/src/agent/onefuzz/src/input_tester.rs#L133-L198) and `run_cmd`. We checked into test_input_debugger method and did not find any debug statements to track the crashes. We did notice the debug statements within run_cmd and string search for these debug statements in app insights did not produce any results.

**Comment by chkeita** [comment]
my colleague @ranweiler just added a project to test inputs in the code base. If you are familiar with rust,  you should be able to clone the repo and use it to test your binaries and validate that it is producing a crash that we can detect. The instructions are in the description.

https://github.com/microsoft/onefuzz/pull/1624

**Comment by prasanthbalaji** [comment]
Hi @chkeita, Initially, with out a timeout value crash was NOT detected, after we aded a timeout value of 70 we were able to get crashes. Previously, we had provided target_timeout up to 250 sec to onefuzz job still job did not find the crash.
What is the default timeout value ?

![image](https://user-images.githubusercontent.com/6666424/151850248-f88f8094-8dfd-4bcf-be28-973582bc8df9.png)

**Comment by chkeita** [comment]
The default timeout for testing the input is [5 seconds](https://github.com/microsoft/onefuzz/blob/809db31186ec716fa7fd3a7fb9ac7b188ffe2c34/src/agent/onefuzz/src/input_tester.rs#L23).

**Comment by prasanthbalaji** [comment]
Yes, If I use test-input.exe with a timeout parameter value of 70 sec it is able to detect crash. If I don't use any timeout parameter test-inout.exe it could not detect the crash. 
In all my `onefuzz` jobs I was never successful in getting a crash even after I set `target-timeout` value to 250 sec.

I had used same exe files and input files for testing in above three scenarios.

**Comment by chkeita** [comment]
Are you running test-input.exe on the node VM itself or locally ?

**Comment by prasanthbalaji** [comment]
Hey @chkeita, We got this issue resolved. Issues was with our exe, after application is installed and when the application loads for the first time a data privacy acceptance pop-up comes up, this pop-up needed a manual click. After we figured out a way to suppress this pop-up after installation, we are seeing the crashes in the job.
