### ISSUE TITLE
Fix typo in x86-32 VC redistributable installation command

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1609]
There is a [typo in the `onefuzz.ps1`](https://github.com/microsoft/onefuzz/blob/main/src/runtime-tools/win64/onefuzz.ps1#L168) node setup script run by the Azure Custom Script Extension machinery (`s/WindowSytle/WindowStyle`).

The default PowerShell error action is [`Continue`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.2#erroractionpreference), and we don't override it, so this doesn't actually cause any issues unless an x86-32 target runs on the node _and_ assumes the presence of the VC redistributable.

**Comment by tevoinea** [comment]
Fixed in #1625
