### ISSUE TITLE
Report LibFuzzer `out-of-memory` crashes based on `-rss_limit`

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1632]
The `-rss_limit_mb` and related `-malloc_limit_mb` LibFuzzer parameters allow treating test inputs as faults if the fuzzer memory usage exceeds the limits / requests too much heap memory. Right now, the task worker agent is unaware of this fault type, and so we observe the fuzzer process exit as an error in the fuzzer itself.

Extend our ASAN / fuzzer log parsing to catch this case. We need to be mindful that it will only repro via parsing LibFuzzer crash logs, not under a debugger.

Example line found in a crash log:
```
SUMMARY: libFuzzer: out-of-memory
``` 

AB#39993855

**Comment by Porges** [comment]
Rolling this into #2480. Note that out-of-memory bugs with libfuzzer are often (almost always) legitimate bugs in the target executable and not in libfuzzer itself.
