### ISSUE TITLE
How do I provide defaults to --setup_dir and --target_options

### ISSUE THREAD

**Issue by nageshn66** [microsoft/onefuzz#1639]
## Information

- Onefuzz version:4.0
- OS:Mac

## Provide detailed reproduction steps (if any)

1. I want to start onefuzz job using template command,  oneuzz template libfuzzer basic where I want to pass options --setup_dir and --target_options
2. But, my config file might have no values configured for these options(no paths specified), giving it a default value of null 
3. When the job is invoked using this template, get an error : saying unrecognized argument, it is happy if I pass a definite path to specify.

Question: Can I use options setup_dir and target_options with null or empty string values??

### Expected result

To ingore these options and continue when there is null or empty string value.

### Actual result

unrecognized argument error

**Comment by mgreisen** [comment]
@nageshn66 Please give the invocation you used (redacted as needed) and the shell and OS your using.
