### ISSUE TITLE
macOS clang builds incorrectly determined as windows

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/onefuzz#1652]
## Information

- Onefuzz version: 5.0.0
- OS: macOS 12.0

## Provide detailed reproduction steps (if any)

1. Built a binary with clang and libfuzzer with ASAN on macOS
2. Tried to submit the task to a linux pool

This code identified the binary as Windows because it didn't contain the ELF header:

https://github.com/microsoft/onefuzz/blob/065272191e98205abf5092fe4e7677bdc54521b6/src/cli/onefuzz/templates/__init__.py#L188-L194

```default
onefuzz template libfuzzer basic my-project my-target build-1 linux-pool --target_exe ../../CLionProjects/pyjion/cmake-build-debug/fuzz_target
INFO:onefuzz:creating libfuzzer from template
ERROR:cli:command failed: mismatched os. pool: linux target: windows
```

Realized immediately after that this wouldn't have worked, but others might not've read the small print that macOS isn't supported.

Feel free to close if this won't be fixed since it isn't supported.

If you want to inspect mach-O headers the magics are either `CA FE BA BE`, `FE ED FA CE`, or `FE ED FA CF`

 

AB#39993844

**Comment by mgreisen** [comment]
It would be helpful to simply print an error message.

**Comment by mgreisen** [comment]
We've since removed what little support we had for MacOS. Closing this issue.
