### ISSUE TITLE
Retry managed identity token acquisition attempts per docs

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#168]
Managed pool VMSS nodes use a system-assigned managed identity to acquire access tokens for requests to the service.

The docs for the REST API used to acquire these tokens has [specific guidance](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#retry-guidance) around when and how to retry (with backoff). Implement this in the token acquisition code.

**Comment by bmc-msft** [comment]
The changes in #153 include retry that is in line with the azure guidance for retry.  Considering this done.
