### ISSUE TITLE
Improve debuggability of missing shared libraries

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1706]
When a user creates a target with shared library dependencies that are missing at runtime, the error message is uninformative.

For example, on Windows, a missing DLL results in an error like:
```
[2022-03-10T21:37:46Z ERROR onefuzz_agent::managed::cmd] error running task: fuzzer does not respond to '-help=1'. output:Output { status: ExitStatus(ExitStatus(3221225781)), stdout: "", stderr: "" }
Error: fuzzer does not respond to '-help=1'. output:Output { status: ExitStatus(ExitStatus(3221225781)), stdout: "", stderr: "" }
```
Note that `3221225781` == `0xc0000135`.

Instead, we should as many of the following as possible:
- Translate the `-help=1` check error code to something more informative (missing DLL)
- Return information about shared library search paths
- Identify all (or at least the first) runtime-missing DLL(s) (for example, as indicated by `ldd -v`)

Note that the existence of setup scripts and OneFuzz-adjusted `$PATH` env vars complicate this, and mean we can't perform this check based only on the target and setup container contents. 

AB#39993811

**Comment by mgreisen** [comment]
@ranweiler Can this be closed or is there still more work to be done?

**Comment by ranweiler** [comment]
I think this one can be considered done, modulo specific edge cases or bugs.
