### ISSUE TITLE
Provide the ability to download the logs specific to a job

### ISSUE THREAD

**Issue by chkeita** [microsoft/onefuzz#1711]
The proposal is to redirect agent logs to a blob and make it available via the cli.

## On the agent
The redirection can happen in [onefuzz-telemetry](https://github.com/microsoft/onefuzz/blob/194e7d0e9ec09fb78dae688cc549b63641a1b69e/src/agent/onefuzz-telemetry/src/lib.rs#L542) by adding a logic to upload to an [append blob](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-append-blobs). 
We should consider splitting the blob into mutliple files to prevent the creation of single very large blob file. The `x-ms-blob-append-offset` property of the [Append block](https://docs.microsoft.com/en-us/rest/api/storageservices/append-block) can provide the data needed to decide to create a new log file. 

## In the cli
cli work will be done in #1714

**Comment by tevoinea** [comment]
Are we going to set a retention period for these blobs as well? We could probably mirror log analytics and do 90 days.
