### ISSUE TITLE
log analytics cost exceeds the cost of the VMs

### ISSUE THREAD

**Issue by Sinderella** [microsoft/onefuzz#173]
## Information

- Onefuzz version: 1.3.1
- OS: Ubuntu 20.04 docker container on macOS

## Details

I followed the instructions in the [Getting Started](https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md#deploying-jobs) guide and it turns out that the log analytics cost exceeds the cost of the VMs after running for 24 hours as shown below:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/1926450/96455123-af9ed500-1214-11eb-9404-7709ba6f9d7e.png">

I am not sure if this is expected, but I don't think it is great having to pay for logs much more than the computational cost itself. My rough understanding is that the agent is reporting everything in realtime which would produce a huge amount of logs to process. Would it be possible to somehow reduce the logging cost by introducing some delays between reports?

To me, realtime stats are good when we're fuzzing something that requires monitoring to improve our harnesses and corpus. However, there are cases that we need to run it for days if not weeks where we don't expect any crash to occur, just use it as some kind of a baseline. Logging too much would create some unnecessary cost.

**Comment by bmc-msft** [comment]
We're working on a number of changes that will reduce logging.  Some of which have already been merged (See #175, #170, #160, #159).

We will continue to streamline how much data is logged in the future.

**Comment by bmc-msft** [comment]
With [1.3.0](https://github.com/microsoft/onefuzz/releases/tag/1.3.0), I saw a similar ratio to what you identified.

With [1.3.2](https://github.com/microsoft/onefuzz/releases/tag/1.3.2), I get the following:

![image](https://user-images.githubusercontent.com/41130664/96743844-683e5300-1392-11eb-95a4-fa3900a621d0.png)

**Comment by bmc-msft** [comment]
1.4.0 implemented service level application insights sampling after 20 events per second.  With these issues, I consider this issue resolved.  If this issue persists for you after upgrading to 1.4.00 or later, please re-open this issue.
