### ISSUE TITLE
OneFuzz CLI command `onefuzz status pool <pool_name>` fails

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#1730]
Version: 5.2.0 (both API and CLI)

Running `onefuzz status pool <pool_name>` consistently fails with the following error:

```
onefuzz status pool <pool_name>
ERROR:cli:command failed: too many values to unpack (expected 2)
``` 

AB#39993806

**Comment by stishkin** [comment]
➜ ./onefuzz.exe --version
onefuzz.exe 5.2.0

➜ .\onefuzz.exe status pool "default"
{
    "node_state": {
        "free": 20
    },
    "tasks": {}
}

I could not repro on Windows from powershell

@jagunter  what OS and shellS are you using ?

**Comment by jagunter** [comment]
This is on Ubuntu 18.04 (via WSL). Apologies should have noted that earlier. Testing further, it appears only some pools are affected.

**Comment by jagunter** [comment]
Running the query with `-vvv` reveals the issue in the stack trace:

```
ERROR:cli:traceback: Traceback (most recent call last):
ERROR:cli:traceback:   File "$HOME/.pyvenv/onefuzz/lib/python3.10/site-packages/onefuzz/cli.py", line 586, in execute_api
ERROR:cli:traceback:     result = call_func(args.func, args)
ERROR:cli:traceback:   File "$HOME/.pyvenv/onefuzz/lib/python3.10/site-packages/onefuzz/cli.py", line 74, in call_func
ERROR:cli:traceback:     return func(**myargs)
ERROR:cli:traceback:   File "$HOME/.pyvenv/onefuzz/lib/python3.10/site-packages/onefuzz/status/cmd.py", line 49, in pool
ERROR:cli:traceback:     task_id, _task_state = entry
ERROR:cli:traceback: ValueError: too many values to unpack (expected 2)
ERROR:cli:traceback:
ERROR:cli:command failed: too many values to unpack (expected 2)
```

The query likely succeeds when there are no tasks in the pool to unpack.

**Comment by jagunter** [comment]
Issue is still present in `5.16.0`
