### ISSUE TITLE
Large file rdamsa fuzzing azcopy issue

### ISSUE THREAD

**Issue by prasanthbalaji** [microsoft/onefuzz#1741]
## Information

- Onefuzz version: 4.0.0
- OS: Windows

## Provide detailed reproduction steps (if any)

1. Submit onefuzz radamsa job with an input folder containing large file ~75mb.
2. rdp into generator_generator task 
3. open event viewer to see below error

### Expected result

fuzz successfully.  

### Actual result

got and error in event viewer, below is the log.
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/6666424/161606466-5643919f-78f0-469f-854f-3efa1fca76c5.png">

**Comment by mgreisen** [comment]
Sometimes of these errors are transient. Can you post the console output when the upload fails?
