### ISSUE TITLE
[Refactor] queue_file_changes Azure App Function

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#1754]
Refactor the QueueFileChanges function and required sub classes to C#. Validate by disabling the python function and enabling the .net function in a testing environment before deploying the change to production.

**Blocked on templating**:
* https://github.com/microsoft/onefuzz/blob/447f1813b1c3fac0e932c575f51bbe1538194936/src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs#L37
* https://github.com/microsoft/onefuzz/blob/447f1813b1c3fac0e932c575f51bbe1538194936/src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs#L45
* https://github.com/microsoft/onefuzz/blob/447f1813b1c3fac0e932c575f51bbe1538194936/src/ApiService/ApiService/onefuzzlib/NotificationOperations.cs#L49

AB#39993385

AB#40263775

**Comment by chkeita** [comment]
@tevoinea Can we keep the issue open until we have  full check pr pass with the changes integrated.
