### ISSUE TITLE
Code coverage summary includes non-existent source files

### ISSUE THREAD

**Issue by mgreisen** [microsoft/onefuzz#1766]
When producing the Cobertera XML file, coverage data is included for files that are not available in the repo. These include files in the paths 
- d:/a01/_work/4/s/src/vctools/crt/asan/llvm/compiler-rt/lib/asan
- d:/a01/_work/4/s/src/vctools/crt/sanitizers_support/libsancov
- all files under vccrt
- oss/libfuzzer/10.0.0/src/compiler-rt/lib/fuzzer

We should exclude these kinds of paths/files if possible, so as to not clutter the report. 

We also produce a path "Invalid file format:" with no files. This is unactionable by the dev reviewing the coverage data. 
 

[AB#35934](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/35934)

**Comment by ranweiler** [comment]
Split into:
- [ ] #1774 
- [ ] #1775 
- [ ] #1776

**Comment by Porges** [comment]
Closing this. We now have the ability to allowlist sourcefiles if any coverage is not wanted.
