### ISSUE TITLE
Handle empty source file paths when generating Cobertura

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1775]
Morel likely than invalid source file paths (i.e. lacking a file name component), we have have empty/all-whitespace paths.

Handle this in our [code for getting parent pants](https://github.com/microsoft/onefuzz/blob/5aceb258435954343306909cefd82eb0a71f29b5/src/agent/coverage/src/cobertura.rs#L70-L79).

If there is no actually-actionable data we can give the user in the Cobertura report (as in the non-empty case), it probably makes the most sense to just skip those coverage sites in the XML generation (though logging a warning that includes the name of the module and/or PDB file). 

AB#35931

**Comment by Porges** [comment]
This is now checked by the `FilePath` type
