### ISSUE TITLE
Enable allow-listing source files in Cobertura generation

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1776]
Even if we want more expansive coverage recording in general, even at the source level, our Cobertura XML reports will typically need to be scoped to a specific repo.

Allow a separate mechanism for enabling a prefix-based allowlist. Permit the use of multiple prefixes, and do not generate XML for any source files that do not match the prefix. 

AB#35930

**Comment by mgreisen** [comment]
We now have allow lists that are up-stream from the cobertera generation (which seems appropriate). Closing this work item as implementing this is unnecessary. 

@ranweiler FYI.
