### ISSUE TITLE
Avoid local data in fallback disassembly

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1799]
If no coverage instrumentation is available, but private symbols are available, we fall back to an static, best-effort CFG recovery for target modules.

However, in this mode, coverage recording is dangerously intrusive, due to the use of software breakpoints. For example, if an MSVC-generated PDB provides a procedure symbol whose size includes local jump tables, we will attempt to extract a CFG from the data. If we recover even a single (bogus) block, we may attempt to set a soft breakpoint in data, causing runtime failures.

Avoid this, even if it results in degraded CFG approximation. 

AB#39992634

**Comment by mgreisen** [comment]
@ranweiler is this still relevant with the code coverage changes you've made?
