### ISSUE TITLE
Full path of the input file

### ISSUE THREAD

**Issue by tunz** [microsoft/onefuzz#18]
In the command replacement, `{input}` provides a relative path of the input file such as `generator_tmp/input`. But, some binaries requires a full path of the file.

I think `{input}` needs to be replaced to the absolute path rather than a relative path. What do you think?

**Comment by bmc-msft** [comment]
I'm in support.

Using the full, canonicalized paths would address multiple issues beyond this one, including targets that change their directory prior to opening the input file.  

We probably want to update all of the Path variables in [Expand](https://github.com/microsoft/onefuzz/blob/main/src/agent/onefuzz/src/expand.rs) should be updated to support the full canonicalized path.
