### ISSUE TITLE
investigate replacing python function code with rust

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#184]
The [Azure SDK for Rust](https://github.com/azure/azure-sdk-for-rust) continues to make large strides forwards, making it a potential avenue moving forwards.

Many, but not all, of our prerequisites are available in rust.

### Currently available
* [azure.storage.blob](https://github.com/Azure/azure-sdk-for-rust/tree/master/sdk/storage)
* [azure.storage.table](https://github.com/Azure/azure-sdk-for-rust/tree/master/sdk/storage)
* [azure.mgmt.compute](https://github.com/Azure/azure-sdk-for-rust/tree/master/services/mgmt/compute)
* [azure.mgmt.resource](https://github.com/Azure/azure-sdk-for-rust/blob/master/services/mgmt/resources/src/package_resources_2020_06/operations.rs#L3815)
* [azure.mgmt.storage](https://github.com/Azure/azure-sdk-for-rust/tree/master/services/mgmt/storage)
* [azure.identity](https://github.com/Azure/azure-sdk-for-rust/tree/master/sdk/identity)
* [azure.mgmt.operationalinsights](https://github.com/Azure/azure-sdk-for-rust/tree/master/services/mgmt/operationalinsights) (known as azure.mgmt.loganalytics in python)

### Alternatives available
* jinja2: [tera](https://github.com/Keats/tera), [askama](https://github.com/djc/askama)
* opencensus: [appinsights-rs](https://github.com/dmolokanov/appinsights-rs)
* pyjwt: [jwt](https://crates.io/crates/jwt) - NOTE: We don't need full token validation, that's done by App Services.  We only need to extract the appid & OID
* requests:  [reqwests](https://crates.io/crates/reqwests) - used for Teams webhook integration
* github3.py: [octocrab](https://docs.rs/octocrab/0.5.0/octocrab/issues/struct.IssueHandler.html)

### Currently in progress:
* [azure.storage.queue](https://github.com/Azure/azure-sdk-for-rust/issues?q=is%3Aissue+is%3Aopen+azure+storage+queue) - The basic functionality for iterating over a queue exists, but managing queue creation does not yet.

### Missing
* azure.mgmt.network - required for creating networks used by scalesets (implemented in autorust, but not available in the SDK yet: https://github.com/ctaggart/autorust/blob/master/codegen/examples/gen_mgmt.rs#L62 )
* azure.devops

### Investigate removing
* azure-mgmt-cosmosdb: This doesn't appear to be imported
* azure.graphrbac: implements is_member_of, which is better served using App Roles (see #147 )
* azure.keyvault: This doesn't appear to be imported [rust impl](https://github.com/Azure/azure-sdk-for-rust/tree/master/sdk/key_vault)
* azure.servicebus: This doesn't appear to be imported
* azure.mgmt.cosmosdb - We could move to all tables are managed in the Arm template and we use [azure.storage.table](https://github.com/Azure/azure-sdk-for-rust/tree/master/sdk/storage) as the client. 

AB#39994746

**Comment by bmc-msft** [comment]
There is an upstream work-around for azure.mgmt.network available upstream that we should investigate:

https://github.com/ctaggart/azure-sdk-for-rust/pull/1#issuecomment-718778004

**Comment by mgreisen** [comment]
Closing this issue as we've decided to move to C#.
