### ISSUE TITLE
[C# port] Desrializing pool architecture crashes Enum conversion in Json Desrializer

### ISSUE THREAD

**Issue by stishkin** [microsoft/onefuzz#1908]
Create a pool using OneFuzz CLI

Retrieve the pool using C# API (GetPoolByName)

Pool architecture is set to "x86_64" in the table. 

Entity Converter
``` C#
            var stringValues =
                entity.GetString(fieldName).Split(",", StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(CaseConverter.SnakeToPascal);
```

Will convert this to 
"X8664"
and conversion to enum will fail with

"Requested value 'X8664' was not found."

**Comment by stishkin** [comment]
To repro the issue this PR needs to be merged: https://github.com/microsoft/onefuzz/pull/1909

since it fixes the Pool definition in Models.cs

**Comment by chkeita** [comment]
@stishkin use [SkipRenameAttribute](https://github.com/microsoft/onefuzz/blob/91922ce01a94b031340bce45c4f6702c98ec6cc9/src/ApiService/ApiService/OneFuzzTypes/Model.cs#L29) to tell the orm to not convert the enum value

**Comment by stishkin** [comment]
@chkeita

Added following code:
``` C#
[SkipRename]
public enum Architecture {
    x86_64
}
```

still same issue

**Comment by chkeita** [comment]
OK that is a bug. The Orm is not reading this attribute for table Enitities
