### ISSUE TITLE
Service Exception: Exception while executing function: Functions.queue_signalr_events

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#1913]
Filing bug with service exception information. These were bugs were detected by the new Azure Monitor alerts. 
 
## OneFuzz Information
- Onefuzz version: 5.3.0

## Service Exception Information
- Exception Type: System.Net.Http.HttpRequestException
- Message: Exception while executing function: Functions.queue_signalr_events. Response status code does not indicate success: 502 (Bad Gateway).
- Time of the Error: 2022-05-09T05:09:06.272Z
- Operation Name: System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode
 

AB#39992455

**Comment by mgreisen** [comment]
Closing as we haven't seen this in quite a while.
