### ISSUE TITLE
Service Exception: queue_signalr_events. Resource temporarily unavailable. 

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#1915]
Filing bug with service exception information. These were bugs were detected by the new Azure Monitor alerts. 
 
## OneFuzz Information
- Onefuzz version: 5.3.0

## Service Exception Information
- Exception Type: System.Net.Sockets.SocketException
- Message: Exception while executing function: Functions.queue_signalr_events. Resource temporarily unavailable.
- Time of the Error: 2022-05-08T10:41:36.195Z
- Operation Name: queue_signalr_events
 

AB#39956438

**Comment by mgreisen** [comment]
This appears to have been addressed as we haven't see this in a while.
