### ISSUE TITLE
Users aren't alerted to Notification failures

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1941]
OneFuzz has both webhook events and _notifications_. When notifications are configured, but fail to send, the failure is logged internally to an instance, but is otherwise silent. For example, the associated task is not failed. This can happen if a user has a custom analysis task that generates a structured file (like a crash report), or if they have an ADO Notification template that is malformed.

Make it so that a failed notification is observable to end users in a way that does not depend on task or user-generated data. For example, we could add webhook events for notification failures specifically, which an external service could consume and use to send emails. This could be generalized to other backend failures. 

AB#39956411

**Comment by mgreisen** [comment]
@nharper285 please be sure to reference this issue in your PR using "closes".
