### ISSUE TITLE
Upgrade to CodeQL V2

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#1963]
We're currently using CodeQL V1 which will be deprecated in December 2022.

> [^1] [Analyze (python)](https://github.com/microsoft/onefuzz/runs/6498080801?check_suite_focus=true#step:4:27)
CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/ 

We should:

- [ ] Upgrade to V2
- [ ] Add c# as a scanning language [^2] https://github.com/microsoft/onefuzz/blob/b4e5c7c79e39839a0c1e63b6f72f82839d5b94bf/.github/workflows/codeql-analysis.yml#L17

[^1]: https://github.com/microsoft/onefuzz/actions/runs/2348553071
[^2]: https://docs.microsoft.com/en-us/dotnet/architecture/devops-for-aspnet-developers/actions-codeql

**Comment by nharper285** [comment]
[Closing] https://github.com/microsoft/onefuzz/pull/1984
