### ISSUE TITLE
C# conversion of `agent_events`

### ISSUE THREAD

**Issue by Porges** [microsoft/onefuzz#2031]
Convert the `agent_events` Azure Function to C#, and release to production.

This Function handles events emitted by the OneFuzz agent from nodes.

AB#39955736

**Comment by mgreisen** [comment]
@Porges please add a description

**Comment by chkeita** [comment]
@Porges Reopening this issue. We keep the migration issue open until it is deployed to prod.

**Comment by Porges** [comment]
Now released.
