### ISSUE TITLE
onefuzz notifications list always returns the complete list of containers

### ISSUE THREAD

**Issue by puhley** [microsoft/onefuzz#2074]
## Information

- Onefuzz version: 5.5.0
- OS: Mac

## Provide detailed reproduction steps (if any)

1. When using `onefuzz notifications list --container container_name`, the command will always return the complete list of container notifications. This can also be seen when using OneFuzz as a Python SDK and calling `onefuzz.notifications.list(container=list_of_container_names)`. 

### Expected result

The expected result is that filtering is applied to only return the notification configurations for the specified containers.

### Actual result

All notification configurations are returned.

### Root cause analysis

Starting at the bottom and working backwards, the Azure Blob Tables query filter is created by the function  `build_filters`: https://github.com/microsoft/onefuzz/blob/2fcb4998887959b4fa11894a068d689189742cb1/src/api-service/__app__/onefuzzlib/orm.py#L123

Specifically, the query filter is created by this section of the `build_filters` code:
```
        elif all(isinstance(x, SAFE_STRINGS) for x in values):
            parts = ["%s eq '%s'" % (field_name, x) for x in values]
```

I have confirmed that this code works correctly if `build_filters` receives a `cls` of the type `Notification` and a `query_args` value that is an array of Containers: `[Container(container_name_1), Container(container_name_2), ...]`. If it receives these parameters, then the appropriate Azure Blob Tables filter is produced and everything works. However, I believe what is happening is that the `build_filters` code is not receiving an array of Containers. This results in the code passing through to the `else` statement which results in an empty filter.

The request comes in via the API service's Notifications class: https://github.com/microsoft/onefuzz/blob/4ecd43fc0fb80d0ff5511c2d9a61f702c6c55aed/src/api-service/__app__/notifications/__init__.py#L21

The Notifications class then calls `parse_uri` using `NotificationSearch` as the `cls` value: https://github.com/microsoft/onefuzz/blob/main/src/api-service/__app__/onefuzzlib/request.py#L103
```
    data = {}
    for key in req.params:
        data[key] = req.params[key]

    try:
        return cls.parse_obj(data)
    except ValidationError as err:
        return convert_error(err)
```

The `NotificationSearch` class has a `container` object that is a list of Containers: https://github.com/microsoft/onefuzz/blob/424ffdb4b5f2f555b115a6096c1d23e6d3ecdd82/src/pytypes/onefuzztypes/requests.py#L48

```
class NotificationSearch(BaseRequest):
    container: Optional[List[Container]]
```

The NotificationSearch class is intended to be the array of Containers that `build_filters` expects. However, the issue appears to be that the NotificationSearch `parse_obj` call within `parse_uri` is not correctly converting the array of container name strings from the HTTP request into a corresponding array of Containers.

When doing a local test of:
```
   from onefuzztypes.requests import NotificationSearch

    data = {}
    data['container'] = ['oft-unique-reports-a0b4205c5b3d533331aeb1a2cd34e56f', 'oft-unique-reports-6c028db0389a51234d512f5123ab45cd']

    request = NotificationSearch.parse_obj(data)

    for entry in request.container:
          if isinstance(entry, Container):
               print("Pass")
          elif isinstance(entry, str):
               print("Fail")
```

The result is that the request.container field is an array of strings. Since it is an array of strings, it fails to match the `isinstance` clause in `build_filters` and an empty filter is returned. This leads to all of the results being returned regardless of whether the container fields are specified.

To fix this, I believe that the `parse_uri` code needs to be refactored to convert the strings to Containers since it appears that the pydantic `parse_obj` method is not automatically converting them into Containers.

AB#36010

**Comment by stishkin** [comment]
Might address this in C# port

**Comment by puhley** [comment]
Out of curiosity, what is the motivation for the C# port?

**Comment by mgreisen** [comment]
Generally, a sense that we needed a) better performance as the service grows in size and scale, b) a belief that stronger types add to reliability and robustness.

**Comment by mgreisen** [comment]
This appears to have been addressed.
