### ISSUE TITLE
Nodes not appearing in the pool to take on jobs even though they are running

### ISSUE THREAD

**Issue by maxnoka** [microsoft/onefuzz#215]
## Information

- Onefuzz version: 1.3.1
- OS: Windows client, Windows VMs

## Provide detailed reproduction steps (if any)

Follow the getting started guide, with these changes:
- I'm using a trial subscription
- Use Windows as pool OS
- I create a scaleset with size 1
- I use the `simple-libfuzzer` example

### Expected result

When invoking `onefuzz status top` I should see the singular node and the pool and it should take on the libfuzzer tasks.

### Actual result

There are no nodes in the pool, and jobs remain `scheduled` and `waiting`, even after hours of waiting (see below for `onefuzz status top`).

![nodes_not_there_to_take_jobs](https://user-images.githubusercontent.com/16231006/97298654-a8e31400-184b-11eb-8dc8-00f279cf0cf8.jpg)

`onefuzz nodes list` also returns empty `[]`. 

I can see the node as "running" both in the azure portal and also when I check `onefuzz scalesets get <scaleset id here>` (see attached txt for the output to a bunch of list and get commands of the pool and the scaleset).

[onefuzz_pools_scalesets_list_and_get.txt](https://github.com/microsoft/onefuzz/files/5445090/onefuzz_pools_scalesets_list_and_get.txt)

**Comment by bmc-msft** [comment]
Can you check the application insights log for the `machine_id` of your node?  It would be good to see if there was something preventing the agent from starting.

From the Azure Portal, go to your Application Insights instance for `OnefuzzTestInstance`, click on "Transaction search" under "Investigate", from there search for the `machine_id` reported in the response from `onefuzz scalesets get`.  You may need to increase your time range for your query.

**Comment by kevinmoro** [comment]
I have the same issue as @maxnoka described above. When I checked the application insights log for the machine_id i found this reoccuring message: 
``Registration failed: HTTP status client error (401 Unauthorized) for url (https://<websitename>.azurewebsites.net/api/agents/registration?machine_id=<machine_id>&pool_name=pool_windows&version=1.5.0&scaleset_id=<scaleset_id>)
 retrying in 60 seconds``
And sometimes this message is occuring, but less often:
``error running supervisor agent: Unable to register agent``

**Comment by bmc-msft** [comment]
@chkeita, can you take a look at this please?

**Comment by chkeita** [comment]
@maxnoka can you please confirm that you still have the issue an seeing the messages in appinsight as @kevinmoro 

@kevinmoro can you please confirm that the command `onefuzz scalesets list` returns a list where the value of `client_object_id` is not null

**Comment by kevinmoro** [comment]
Yes, I can confirm that the value of ``client_object_id`` is not null. When I execute the command ``onefuzz scalesets list`` this is the result:
[
    {
        "client_object_id": "<client_object_id>",
        "image": "MicrosoftWindowsDesktop:Windows-10:rs5-pro:latest",
        "pool_name": "<pool_name>",
        "region": "westeurope",
        "scaleset_id": "<scaleset_id>",
        "size": 2,
        "spot_instances": false,
        "state": "running",
        "tags": {},
        "vm_sku": "Standard_D2s_v3"
    }
]

**Comment by chkeita** [comment]
@kevinmoro it is possible that the request for registration timed out before we initialized the scalesets in the service. 
Can you try restarting the instances of you scalesets. You should be able to do it with this command
`az vmss restart --resource-group <resource_group> --name <scaleset_id> --instance-ids <instance_id>`
you can get the list of instance ids with this command 
`az vmss list-instances --resource-group <resource_group> --name <scaleset_id> --output table `

**Comment by kevinmoro** [comment]
I restarted the instances of the scalesets but the problem still remains the same. I still don't see any nodes when I execute the command ``onefuzz status top``.

**Comment by chkeita** [comment]
It looks like you are using version 1.5.0. Can you upgrade to [1.6.0](https://github.com/microsoft/onefuzz/releases/tag/1.6.0) and see if the problem persists. We made some changes in the authorization process in that version. 
you will need to shutdown your current scaleset first and create a new one.

**Comment by maxnoka** [comment]
Hi sorry about the lack of attention to this on my side; have been distracted by other projects... Will get back and test with 1.6.0 tomorrow!

**Comment by maxnoka** [comment]
I am seeing the same problem with `1.7.0`. The same messages as @kevinmoro described (`Registration failed: HTTP status client error (401 Unauthorized) for url ...` and `error running supervisor agent: Unable to register agent`). Value of `client_object_id` of the scaleset also not null.

**Comment by chkeita** [comment]
@maxnoka can you try remoting to the machine with the command 
`onefuzz debug scalesets rdp <scaleset_id> <machine_id>`
you will find the machine_id by executing 
`onefuzz scalesets get <scaleset id here>` in the nodes property
 and execute the following powershell script to attempt a manual registration (i am assuming that this is windows machine)
``` PowerShell
$onefuzzinstance = "<your instance name>"
$pool_name = "pool_windows"
$scaleset_id = Invoke-RestMethod "http://169.254.169.254/metadata/instance/compute/vmScaleSetName?api-version=2020-06-01&format=text" -Headers @{Metadata="true"}
$machine_id = Invoke-RestMethod "http://169.254.169.254/metadata/instance/compute/vmId?api-version=2020-06-01&format=text" -Headers @{Metadata="true"}
$token = Invoke-RestMethod -Uri "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2F$($onefuzzinstance).azurewebsites.net" -Headers @{Metadata="true"}

try{
    Invoke-RestMethod -Method POST -uri "https://$($onefuzzinstance).azurewebsites.net/api/agents/registration?machine_id=$($machine_id)&pool_name=$($pool_name)&version=1.7.0&scaleset_id=$($scaleset_id)" -Headers @{ Authorization ="Bearer $($token.access_token)"} -verbose
}
catch {
    Write-Host "registration error: $($_)" 
    Write-Host "registration error message: $($_.ErrorDetails.Message)" 
}
```
This should give us more details on the reason why the registration is failing

**Comment by chkeita** [comment]
Also, do you only see the issue on windows or is it the same on windows too ?

**Comment by maxnoka** [comment]
I ran the powershell script and got the following output 
```
VERBOSE: POST
https://onefuzztestinstance.azurewebsites.net/api/agents/registration?machine_id=<machine id is here>&p
ool_name=pool-windows-dev&version=1.7.0&scaleset_id=<scaleset id is here> with 0-byte payload
VERBOSE: received -1-byte response of content type application/json

events_url                                                      work_queue
----------                                                      ----------
https://OneFuzzTestInstance.azurewebsites.net/api/agents/events https://fuzzg5demfe5tc3uu.queue.core.windows.net/poo...
```

Following that the node finally appears in `onefuzz nodes list` and `status top`!

Have not tested on linux yet... Will try that as wll.

**Comment by maxnoka** [comment]
Not sure if there is something hard coded in the script that I am not seeing, but executing the same script on a different VM in the same scaleset fails with this output:
```
VERBOSE: POST
https://onefuzztestinstance.azurewebsites.net/api/agents/registration?machine_id=3a5d1ccd-98a7-4b5e-ade2-f09ad3d330d9&p
ool_name=pool-windows-dev&version=1.7.0&scaleset_id=de010b12-3368-4253-a8eb-fceccc39a63f with 0-byte payload
registration error: The remote server returned an error: (401) Unauthorized.
registration error message:
```

Furthermore, the node which is now registered still does not take on any tasks.

**Comment by maxnoka** [comment]
No problems with linux scalesets and nodes. Those work fine.

**Comment by chkeita** [comment]
> Not sure if there is something hard coded in the script that I am not seeing, but executing the same script on a different VM in the same scaleset fails with this output:
> 
> ```
> VERBOSE: POST
> https://onefuzztestinstance.azurewebsites.net/api/agents/registration?machine_id=3a5d1ccd-98a7-4b5e-ade2-f09ad3d330d9&p
> ool_name=pool-windows-dev&version=1.7.0&scaleset_id=de010b12-3368-4253-a8eb-fceccc39a63f with 0-byte payload
> registration error: The remote server returned an error: (401) Unauthorized.
> registration error message:
> ```
> 
> Furthermore, the node which is now registered still does not take on any tasks (stays in the `init` status)

does this failure occurs on a newly created node inside the scaleset ? if that is the case you might want to retry after some time.

Here is my current theory about this bug: 
We currently try to register the node for 5 min before giving up. My guess is that your scaleset takes more time than that to come online

**Comment by chkeita** [comment]
also the linux machines are faster to boot that windows, that might explain why you don't see the issue on linux

**Comment by maxnoka** [comment]
Your theory rings true. The windows instances take a very long time to come online. 

> does this failure occurs on a newly created node inside the scaleset ? if that is the case you might want to retry after some time.

How do I go about creating a new node in the scaleset? can I add it via the az cli or does it have to be the onefuzz cli? Could you also elaborate on what might be worth retrying?

**Comment by chkeita** [comment]
nodes can be added (or removed)  by resizing the scaleset with this command 
`onefuzz scalesets update scaleset_id --size <size>`
I wanted to know if the node that cannot register was a new created from that operation. It looks like it was not.
I just wanted you to retry the command I sent you on the node where it failed to see if the issued persisted.
