### ISSUE TITLE
Looks like OneFuzz attempted to modify a wrong work item in ADO 

### ISSUE THREAD

**Issue by stishkin** [microsoft/onefuzz#2169]
`task_type libfuzzer_crash_report`

``` json
{
 "error": {
    "code": 470,
    "errors": [
      "notification failed",
      "TF401346: Invalid Area/Iteration id given for work item NNNNNN, field 'System.IterationId'."
    ]
}
}
```
After looking up the offending work item - that item was not filled by OneFuzz originally and it has nothing to do with OneFuzz, yet it looks like OneFuzz attempted to modify it.

AB#40479355

**Comment by mgreisen** [comment]
It's important to have enough fields in the UniqueFields to identify the specific bug.
