### ISSUE TITLE
Diagnostic Settings Not Enabled for OneFuzz Scaleset

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#2199]
## Information

- Onefuzz version: 5.8.0

## Provide detailed reproduction steps (if any)

Created Scaleset via CLI

### Expected result

_What is the expected result of the above steps?_
Autoscale diagnostic settings automatically set. 

### Actual result

_What is the actual result of the above steps?_
Settings not set. 

AB#40638062

**Comment by tevoinea** [comment]
Closing for now and the next time it happens we can capture some more information (which scaleset, diagnostic logs if available).
