### ISSUE TITLE
New nodes are created when the scalesets state is shutdown

### ISSUE THREAD

**Issue by chkeita** [microsoft/onefuzz#2203]
## Information

- Onefuzz version: 
- OS:

## Provide detailed reproduction steps (if any)

The situation was observed in canary in the scaleset: a0e09e42-da6a-450f-b2a8-656897707508
at the time of writing this here is the result of quering the state of the scaleset twice ( about 10 min apart)
```json 
{
    "client_object_id": "1ab466cd-c6c3-4687-a6ad-00d452f152db",
    "ephemeral_os_disks": false,
    "image": "Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest",
    "needs_config_update": false,
    "nodes": [
        {
            "instance_id": "0",
            "machine_id": "e87924b6-400f-4a44-946e-74c9e2219f2e",
            "state": "busy"
        },
        {
            "instance_id": "1",
            "machine_id": "e5393b4e-b61f-45c6-b1ba-c76b80249553",
            "state": "busy"
        },
        {
            "instance_id": "105",
            "machine_id": "ab51fb3e-b7bf-4c7c-be2c-0def88a23d5b",
            "state": "init"
        }
    ],
    "pool_name": "test_pool_6e133403",
    "region": "westus3",
    "scaleset_id": "a0e09e42-da6a-450f-b2a8-656897707508",
    "size": 5,
    "spot_instances": false,
    "state": "shutdown",
    "tags": {},
    "vm_sku": "Standard_D2s_v3"
}
```

```json 
{
    "client_object_id": "1ab466cd-c6c3-4687-a6ad-00d452f152db",
    "ephemeral_os_disks": false,
    "image": "Canonical:0001-com-ubuntu-server-focal:20_04-lts:latest",
    "needs_config_update": false,
    "nodes": [
        {
            "instance_id": "0",
            "machine_id": "e87924b6-400f-4a44-946e-74c9e2219f2e",
            "state": "busy"
        },
        {
            "instance_id": "1",
            "machine_id": "e5393b4e-b61f-45c6-b1ba-c76b80249553",
            "state": "busy"
        },
        {
            "instance_id": "106",
            "machine_id": "091539a4-9b3b-453e-8173-e77e08a1c5fc"
        }
    ],
    "pool_name": "test_pool_6e133403",
    "region": "westus3",
    "scaleset_id": "a0e09e42-da6a-450f-b2a8-656897707508",
    "size": 5,
    "spot_instances": false,
    "state": "shutdown",
    "tags": {},
    "vm_sku": "Standard_D2s_v3"
}
```

### Expected result

No new node is created because the state of the scaleset is shutdown

### Actual result

The last node is being recreated multiple time even though the scaleset state is `shutdown`
This node will pick up new work but will fails to schedule because the scaleset state is shutdown. 
Eventually, The node itself gets deleted because the service cleans it up (because of the state of the scaleset). 
The node eventually gets recreated then readded to the scale set (possibly because of the autoscale behavior)

AB#40687517

**Comment by mgreisen** [comment]
@chkeita One possible cause is we had an issue when creating the scaling settings where the minimum size of the scaleset was set to 1. This has been addressed and now the minimum size is 0.

**Comment by mgreisen** [comment]
@tevoinea Looking at a repro of this issue. The scaling minimum is set to 0 on the scale set. However as queue items show up in the pool VM's still get spun up. The service denies it work, but there is a bunch of VM flapping. Because there are still VM's doing "real" work in the scaleset, the rules can't be updated (in the portal). I assume that means they can't be updated programmatically either.

**Comment by tevoinea** [comment]
@mgreison It's possible but we need to update the minimum instances in the scale set as we're scaling down.

**Comment by tevoinea** [comment]
Fixed in python and c#
