### ISSUE TITLE
Refactor Scaleset Scaling Params - Change Size to MaxSize

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#2227]
Simple request to update the current CLI commands and parameters for scaleset create. Currently `size` is set to both `default` and `MaxSize`. We propose adding a `default` parameter and setting the meaning of `size` to `MaxSize`. 

**Current:** 
   auto_scale = requests.AutoScaleOptions(
            min=min_instances,
            max=size,
            default=size,
            scale_out_amount=scale_out_amount,
            scale_out_cooldown=scale_out_cooldown,
            scale_in_amount=scale_in_amount,
            scale_in_cooldown=scale_in_cooldown,
        )

**Proposed**: 
   auto_scale = requests.AutoScaleOptions(
            min=min_instances,
            max=size,
            default=default_instances **(new flag),**
            scale_out_amount=scale_out_amount,
            scale_out_cooldown=scale_out_cooldown,
            scale_in_amount=scale_in_amount,
            scale_in_cooldown=scale_in_cooldown,
        )

**Comment by mgreisen** [comment]
Should we rename `size` to `maxsize`?

**Comment by nharper285** [comment]
> Should we rename `size` to `maxsize`? Perhaps `size` is used in other contexts?

Sure!

**Comment by tevoinea** [comment]
Do you mean renaming `size` the CLI argument? Or `size` the property on `Scaleset`? The former should be no issue, the latter is mapped in the ORM so we would need to be careful performing that rename.

Another would would be to keep the mapping from `CLI.size` to `AutoScaleOptions.default` and introduce a new `CLI.max_size -> AutoScaleOptions.max` mapping.

**Comment by mgreisen** [comment]
My thought was to rename the `size` argument in the CLI for greater clarity. We want the AutoScaleOptions.default to be a small number, preferably 1, to keep the number of nodes "spun up" when creating the scale set to a minimum. Otherwise, we wind up with a bunch of nodes spun up that then are deleted (via the scale-in rules).
