### ISSUE TITLE
A corpus scheduling strategy for parallel fuzzing

### ISSUE THREAD

**Issue by gtt1995** [microsoft/onefuzz#2244]
Hello,
        Assigning seeds, i.e., assigning local sub-corpus, at each time for the minimum run unit Fuzzer is a new seed scheduling process, just like the common seed search strategy inside gray-box fuzzy tests. In this process, we need to pay attention to two key points, searching for high-quality seeds to assign to each sub-instance and avoiding task conflicts for each sub-instance. Based on this, I propose a new corpus assignment strategy, this work is based on libFuzzer-fork implementation, which has been received by LLVM community and more detailed description has been accepted by ESEC/FSE, please ask the work Is it useful for the one-fuzz project? If it is feasible, I can send you a pdf of the paper via email.

Thank you for your time!
Looking forward to your response.

AB#36031

**Comment by mgreisen** [comment]
Hi @gtt1995 can you post a link to your paper?

**Comment by gtt1995** [comment]
Hello, Greisen
 This is certainly possible, please allow me to send it to you via email as the paper is still in the unpublished stage.
Thank you for your time.
Best wishes.

**Comment by mgreisen** [comment]
This currently doesn't align with our strategy.
