### ISSUE TITLE
Add app id as Owner to resource group during deployment

### ISSUE THREAD

**Issue by anslutsk** [microsoft/onefuzz#231]
Add app id as Owner to resource group during deployment. Otherwise, I need to manually add it when using deploy-onefuzz-via-azure-devops. The file deploy-onefuzz.yml executes a login using the '--service-principal' option (command below) and it does not work unless I add the app id as an Owner to the RG, which is displayed only when deploying with the option --log_service_principal.

az login --service-principal -u $(ONEFUZZ_SERVICE_URL) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)

I can make the change but wanted feedback before implementing and creating a pull request. I thought I would implement the change in deploy::setup_rbac() but since the RG isn't created yet I think it needs be done during/after the azuredeploy.json template is deployed in deploy::deploy_template(). If adding a parameter to azuredeploy.json would work then I'd also like to point out there is already a parameter named 'clientId' but I think that's a different app id than we need.

If this is not a good idea for deployments by default, for what ever reason we could make it an additional option on the command line. E.g. we add '--add-app-owners' with a description "Add the client id as an Owner to the Resource Group"

**Comment by bmc-msft** [comment]
OneFuzz operates under a least-privilege required model.   

As an example, we explicitly define the roles needed by Azure Functions.   
https://github.com/microsoft/onefuzz/blob/99b69d3e560a0e98416df632a6738223cab8f637/src/deployment/azuredeploy.json#L523-L537

We have explicitly defined the privileges required to deploy OneFuzz and provide an [example role](https://github.com/microsoft/onefuzz/blob/main/src/deployment/deployment-role.json) that includes the least privileges required.

**Comment by bmc-msft** [comment]
Per offline discussion, we've included the `--update` in the deploy script to not require admin privs.

**Comment by bmc-msft** [comment]
@anslutsk, I believe this issue can be resolved, can you confirm?

**Comment by anslutsk** [comment]
The issue should not be closed since the service principal still needs to be added manually to the RG with the correct privileges.

**Comment by bmc-msft** [comment]
Revisiting your first message, it appears that you want to re-use the service principal for the OneFuzz Azure Function for deployment.  Is that correct?

**Comment by anslutsk** [comment]
That is one simple way to resolve the feature request but since that encourages abuse/reuse of the identity, it could be enabled with an option during deployment --add_deploy_roles_to_rg.

If this is not a suitable solution then it could be achieved a different deploy option --create_upgrade_ident or something, that would create a _new_ app registration which is added to the RG with the proper roles.

**Comment by bmc-msft** [comment]
I believe I understand your goal now.  I believe you want to create a service principal appropriate for continually deploy a OneFuzz instance in an automated fashion, such as on every release.

Does `az ad sp create-for-rbac` meet your needs for this? (See: [Azure CLI Tutorials](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli))

If you would like to contribute a new tool to manage such a service principal rather than relying on `az-cli`, I think that would be appropriate as an additional tool in the `contrib` directory, similar to the Azure Devops deployment pipeline.
