### ISSUE TITLE
C# port should enforce missing fields in Json deserialization

### ISSUE THREAD

**Issue by stishkin** [microsoft/onefuzz#2314]
POSTing following JSON to Pool APIs in C#
``` json
{
  "name": "FT-DELETE-4812d4da-a9ab-40e1-88f1-2d9e148254fa",
  "oss": "linux",
  "arch": "x86_64",
  "managed": true
}
```
with typo for "OS" will succeed with setting OS to Windows

Meanwhile Python endpoint fails creation with error:
```json
{"code": 450, "errors": ["os: field required"]}
```

ORM must enforce that all fields are present

AB#41119374

**Comment by Porges** [comment]
Not currently possible: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-6-0#missingmemberhandling
