### ISSUE TITLE
Add notification_id to logging for ADO notifications. Use custom events. 

### ISSUE THREAD

**Issue by mgreisen** [microsoft/onefuzz#2421]
## Information

- Onefuzz version: 5.12
- OS: n/a

## Provide detailed reproduction steps (if any)

We recently added some additional logging in 5.12 to show where we create and update ADO work items. We now log the job and task id's and the work item number which is being created or updated, which is great.

However, it's not possible to connect the logs with the notification object in the system. We need to also log the notification_id. 

Further, debugging these things with a trace message is painful. We should log these events with a custom event(s). It would be lovely if the job_id, work item number, notification_id, etc were logged as fields in the customdimention so they are searchable. 

AB#41412760

**Comment by mgreisen** [comment]
Additionally we should add the ADO Organization and Project as tags in the customDimension.

**Comment by tevoinea** [comment]
ADO notification logging has been improved over several PRs like #2653 and #2508.
