### ISSUE TITLE
OneFuzz 5.12 Dotnet job fails w/ 'Missing Shared Libraries'

### ISSUE THREAD

**Issue by ansuter** [microsoft/onefuzz#2457]
## Information

I followed the dotnet example, but cannot get a job to run on onefuzz 5.12. Are the shared libraries supposed to be part of my proj? 

- Onefuzz version: 5.12
- OS: Linux

## Provide detailed reproduction steps (if any)

1. Build dotnet proj
```
~/.dotnet/dotnet build repo/src/FuzzTestManaged/FuzzTestManaged.csproj -c Release -r linux-x64 -f net6.0 -p:PublishSingleFile=true --self-contained true -o ~/fuzzer
```
 
2. libfuzzer-dotnet
```
clang-12 -fsanitize=fuzzer ~/libfuzzer-dotnet.cc -o ./repo/bin/Release/FuzzTestManaged/libfuzzer-dotnet
```

3. Run Command
``` 
onefuzz template libfuzzer dotnet fzproj fzmg build-1 fuzzer-nix-pool ./repo/bin/Release/FuzzTestManaged FuzzTestManaged
```

4. View logs

### Expected result

I'd expect the libraries to be there

### Actual result

[2022-09-28 15:15:50.829568103 UTC] ERROR: error running task: fuzzer does not respond to '-help=1'. missing shared libraries: libgcc_s.so.1, libpthread.so.0, libm.so.6, libdl.so.2, librt.so.1, libstdc++.so.6, libc.so.6. output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "setup/libfuzzer-dotnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by setup/libfuzzer-dotnet)\n" }

AB#41556661

**Comment by Porges** [comment]
I believe this is due to building on a newer version of Ubuntu and then running on the default (18.04) version that we deploy. Note that `--self-contained true` does not produce a fully statically-linked version of the binary. 

Instead of `-r linux-x64` can you try targetting the specific version that your nodes are running — probably `ubuntu.18.04-x64`.

**Comment by Porges** [comment]
We should include this in the documentation.
