### ISSUE TITLE
Update CLI --client_secret error message

### ISSUE THREAD

**Issue by mgreisen** [microsoft/onefuzz#2494]
## Information

- Onefuzz version: 5.15
- OS: n/z

## Provide detailed reproduction steps (if any)

Including the parameter --client_secret in the command line results in the error
`onefuzz.exe: error: unrecognized arguments: --client_secret <secret>`

The client secret has been moved into an environment variable in PR #1918. We need to improve the error message. 

AB#41684238

**Comment by kananb** [comment]
The help page for the `onefuzz config` command no longer lists --client_secret as an optional argument.
