### ISSUE TITLE
Support target_options with leading dashes

### ISSUE THREAD

**Issue by elee** [microsoft/onefuzz#250]
Targets that require options with leading dashes (-) are not supported by OneFuzz's `--target_options` flag.

As an example consider a fuzzing Target that accepts two params:

    $ target-exe --input-file foo --input-port 8080

Attempting to fuzz this with the `afl basic` template is not possible or supported, a naive attempt to supply these would be:

    $ onefuzz template afl basic <project> <job> <pool> --target_exe target-exe --inputs target-inputs --target_options "\"--verbose\", \"--input-file @@\", \"--input-port 8080\""

Similarly, `supervisor_options` does not take flag style arguments either.

**Comment by bmc-msft** [comment]
The upcoming changes to templates will support this via:

```
onefuzz job_templates submit afl_linux PROJ NAME BUILD linux --parameters '{"user_fields": {"target_options": ["--verbose", "--input-file @@", "--input-port 8080"]}}'
```

Note, you will be able to specify the parameters via file as well.
```
$ cat params.json
{
    "user_fields": {
        "target_options": ["--verbose", "--input-file @@", "--input-port 8080"]
    }
}
$ onefuzz job_templates submit afl_linux PROJ NAME BUILD linux --parameters @./params.json
```
