### ISSUE TITLE
Bulk delete NodeMessages

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#2509]
What we do today:
https://github.com/microsoft/onefuzz/blob/d519f0a44b966d680271c8470db2213c46c330a4/src/ApiService/ApiService/onefuzzlib/NodeMessageOperations.cs#L34-L39

What we should do:
```sql
DELETE * WHERE PartitionKey == machineId;
```

AB#41768785

**Comment by tevoinea** [comment]
Alternatively:

* We can set a maximum (100?) messages to delete so that we don't spend too much time of the TimerWorkers invocation on deleting `NodeMessage` entries
OR
* We can pass off the machineId to another function who's sole purpose is deleting NodeMessages

**Comment by Porges** [comment]
Let's at least make this do batch reads/bulk deletes which is a fairly minor change.

**Comment by chkeita** [comment]
Added bulk delete in #2519
