### ISSUE TITLE
Migrate from Ubuntu 18.04 to Ubuntu 20.04 

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#2532]
Github will deprecate the use of 18.04. This will force OneFuzz to do the same so that our build process is not inhibited. 
This is in accordance with Github issue [#6002](https://github.com/actions/runner-images/issues/6002)
Below is a list tracking the migration process from the OneFuzz side and what needs to be updated:

1. Announce (and discuss) migration to Teams
2. Kill 18.04 Scalesets
3. Create new 20.04 scalesets
4. Rebuild Agent
5. Update InstanceConfig references to 18.04
6. Update Models.cs references to 18.04
7. Update doc references to 18.04

AB#41858468

**Comment by Porges** [comment]
The proxy is still built on Github, though.
