### ISSUE TITLE
Running libfuzzer merge for all new inputs at once

### ISSUE THREAD

**Issue by tunz** [microsoft/onefuzz#254]
Currently `libfuzzer_merge` task runs merge for each new input. But, it's very inefficient for us because sometimes it takes hours to run a single merge.

So, we'll need to improve the task or have a new merge task for this case. We'd like to run merge at once after finishing a fuzzing task, or run merge separately once a week while stopping fuzzing tasks to avoid any race condition.

**Comment by bmc-msft** [comment]
We were talking about this on our standup earlier today.

For other tasks, such as Coverage, we support batch & stream processing.  The merge task needs to do this as well.
