### ISSUE TITLE
status top command does not work with C# endpoint

### ISSUE THREAD

**Issue by mgreisen** [microsoft/onefuzz#2572]
## Information

- Onefuzz version: 5.15.1
- OS: n/a

`onefuzz status top` returns

INFO:onefuzz:connecting to signalr
WARNING:SignalRCoreClient:AuthHubConnection
WARNING:SignalRCoreClient:'accessToken'
ERROR:cli:command failed: accessToken

AB#41983706

**Comment by Porges** [comment]
Underlying cause is the `accessToken` is null; still investigating as to why.
