### ISSUE TITLE
OneFuzz CLI command to list containers does not return data if job is not running

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#2574]
## Information

- Onefuzz version: `5.16.0`
- OS: Linux

## Provide detailed reproduction steps (if any)

1. Run `onefuzz jobs containers list <job_id>` for a job that is `stopped`
2. Observe output is `{}`
3. Run `onefuzz jobs containers list <job_id>` for a job that is `running`
4. Observe output has containers

### Expected result

Expect both commands to return populated object.

### Actual result

An empty set is returned if the list is empty.

### Additional Notes

The object is populated for `stopped` jobs if you include `--container_type` in the `onefuzz jobs containers list` command.

AB#41986066

**Comment by chkeita** [comment]
This is the expected behavior because  `onefuzz jobs container list` has a default value for the container_type 
![image](https://user-images.githubusercontent.com/244326/200085674-9301cc23-16b2-4c21-9db5-a61d045ba3b8.png)

**Comment by mgreisen** [comment]
Let's make the --container_type parameter required and not defaulted.
