### ISSUE TITLE
Deploy problem with Azure Cloud Shell

### ISSUE THREAD

**Issue by JsHuang** [microsoft/onefuzz#26]
While following the Getting Started guide  to deploy onefuzz , the command `pip install -r requirements.txt` can not work right. No matching version pyfunctional was found.
```
ERROR: Could not find a version that satisfies the requirement pyfunctional~=1.4.1 (from -r requirements.txt (line 12)) (from versions: 0.6.0, 0.7.0, 0.7.1, 0.8.0, 1.0.0, 1.1.0, 1.1.2, 1.1.3, 1.2.0, 1.3.0)
ERROR: No matching distribution found for pyfunctional~=1.4.1 (from -r requirements.txt (line 12))
```
Change the  the version of pyfunctional package will work, but executing the following `deploy.py` will also failed :
```
huang@Azure:~/onefuzz$ ./deploy.py $REGION $RESOURCE_GROUP_NAME $ONEFUZZ_INSTANCE_NAME $CONTACT_EMAIL_ADDRESS
Traceback (most recent call last):
  File "./deploy.py", line 18, in <module>
    from azure.common.client_factory import get_client_from_cli_profile
ImportError: No module named 'azure.common'
huang@Azure:~/onefuzz$ pip list | grep azure.common
azure-common                          1.1.25
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```
what maybe wrong? how can I fix it?

**Comment by demoray** [comment]
In our internal usage, we did not use the Azure cloud shell.

Some of the libraries used in the deploy tool need to be updated. This may be the underlying cause to the issues you are experiencing, as the Azure cloud shell has multiple extra python libraries installed by default.

We'll look into this.

**Comment by ranweiler** [comment]
Hi @JsHuang! The minimum required Python version for OneFuzz is 3.7. Azure CloudShell only provides up to 3.5, as it is based on [Ubuntu 16.04](https://github.com/Azure/CloudShell/blob/master/linux/base.Dockerfile#L11). It also does _not_ provide [root/sudo access](https://docs.microsoft.com/en-us/azure/cloud-shell/limitations#user-permissions), so you can't install a newer Python (at least via `apt-get`).

As a result, I don't think we can reasonably support this scenario.

Instead, I suggest trying in a different environment with Python 3.7+ and az-cli. If you want to avoid polluting your system Python libraries, I recommend installing the `deploy.py` requirements into a [Python virtual environment](https://docs.python.org/3/library/venv.html#creating-virtual-environments). That's what I do.

**Comment by JsHuang** [comment]
Thanks. I'll try the way as @ranweiler said.
