### ISSUE TITLE
include symbols for the windows agent & supervisor 

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#260]
When debugging the windows agent & supervisor, it would be extremely valuable to have the symbols for the rust code.

**Comment by lzybkr** [comment]
Rust should eventually support /SOURCELINK, but until then, you'll want an easy way to recover the sources too, e.g. by including the git tag/commit in the `--version` output.

**Comment by bmc-msft** [comment]
We already bake the git hash into the binaries.
