### ISSUE TITLE
When creating a bug, generate the OneFuzz commands to download the binaries and crash file

### ISSUE THREAD

**Issue by mgreisen** [microsoft/onefuzz#2603]
We currently create a comment when we create a bug. It looks something like this:

[This input](http://linktofilehere) caused the [fuzz target](http://linkToExe) C:\onefuzz\blob-containers\fuzzpremium02\exename.exe to crash. The faulting input SHA256 hash is 1a591cf3578fb86a7f17b1e80cce9e0ec433b94d71a1297dfc083fa75fe5a9ba

It would be more helpful to include the OneFuzz commands to download the crashing input and the setup container files. 

AB#42134881

**Comment by Porges** [comment]
We also need to point out that some bugs might not be repro-able on local machine. They might have custom setup scripts that require modifying the VM in ways that you would not want to do to your local dev box 🙂
