### ISSUE TITLE
Running OneFuzz on non Azure Based Infrastructure

### ISSUE THREAD

**Issue by mkkeffeler** [microsoft/onefuzz#265]
We are interested in using OneFuzz but we have strict requirements from network perspective. Thus, whatever solution we use needs to run on-premise.

Is this something that exists today, and we are missing docs on? Or work being planned for this? Didn't see much convo on it other than an open PR talking about running it in Docker.

**Comment by bmc-msft** [comment]
Our development for OneFuzz has primarily focused on Azure as a first-class option, though we recognize the need to support non-Azure infrastructure.  There are three major areas that need to be supported to enable on-prem fuzzing:
* Compute (for fuzzing), built on [Azure VMs](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview).  Supporting "bring your own compute" is an upcoming feature.  The Docker PR you mentioned is one strategy we're working on to enable this feature.
* Orchestration, built on [Azure Functions](https://azure.microsoft.com/en-us/services/functions/), which includes built-in support for on-prem.
* Storage & Queues, built on [Azure Storage](https://azure.microsoft.com/en-us/services/storage/), which does not support on-prem on it's own.

Each of these capabilities required are should be available as part of [Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-overview?view=azs-2005), though we have not tested it.

For small deployments, we have internally discussed leveraging [Azurite](https://github.com/azure/azurite), a Microsoft developed lightweight Azure Storage clone primarily used for testing.

**Comment by WSLUser** [comment]
I'd also like to see this be able to run on-prem and also in AWS.

**Comment by l2dy** [comment]
Is it intentional to have this issue closed by a bot?

**Comment by mgreisen** [comment]
@l2dy at this time yes. Since this isn't work that we are currently seeing on our road map. If at a later time we see that this is work we want to take on, we will either re-open this issue or create a new one.
