### ISSUE TITLE
OneFuzz fails with 500 when trying to create a blob container with a name containing upper case letters

### ISSUE THREAD

**Issue by stishkin** [microsoft/onefuzz#2661]
OneFuzz fails with no explanation when trying to create a blob container with a name containing upper case letters.

```
➜ ./onefuzz.exe containers create AbCd
ERROR:cli:command failed: request did not succeed: HTTP 500 -
```

Expected behavior:
Good error message that gives user an explanation on what is allowed and what is not allowed to be used in a container name

AB#42428972

**Comment by tevoinea** [comment]
Is this related to #2652?

**Comment by stishkin** [comment]
C# endpoint should handle this already
