### ISSUE TITLE
Include `CorrelationId` in HTTP responses

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#2672]
It would make it easier to investigate the system behavior for API calls, especially from CLI. If something is failing, we could search for the `CorrelationId` instead of the error string. If a CLI execution isn't behaving as expected, we have a starting point for debugging.

- [ ] Add `CorrelationId` property to `BaseResponse`
- [ ] Output `CorrelationId` from CLI on error responses or when using verbose flag

AB#42495398

**Comment by stishkin** [comment]
https://github.com/microsoft/onefuzz/issues/2444

**Comment by tevoinea** [comment]
Moved the "output correlationid from cli" suggestion into a comment in #2444 and closing this one as duplicate since adding CorrelationId to BaseResponse is just an implementation detail of what's already suggested in #2444.
