### ISSUE TITLE
Deploy Fuzzing for Java Spring Boot and Python Scripts

### ISSUE THREAD

**Issue by crammer94** [microsoft/onefuzz#27]
Hi contributors, I am working at a company which mainly focuses on building Java Spring Boot applications and Python scripts. We are very interested to add fuzzing to our CICD pipelines using OneFuzz - ADO pipeline integration.

Given that, I would like to ask there are plans for adding these types of applications to OneFuzz, or is it already capable of running these types of fuzz targets?

 Since I am currently new to fuzzing, kindly correct me. But, it is to my understanding the current templates (afl, libfuzz, ossfuzz, radamsa) are mainly for CLANG and do not support these types of applications yet.

Looking forward to your response. 

Thank you very much. 

AB#39994814

**Comment by demoray** [comment]
There are fuzzing frameworks for both python and java, such as [pythonfuzz](https://pypi.org/project/pythonfuzz/), and [javafuzz](https://gitlab.com/gitlab-org/security-products/analyzers/fuzzers/javafuzz),  that provide developer focused fuzzing.

Supporting both of those should be relatively straightforward.

**Comment by demoray** [comment]
I'll look into it over the next few days.

**Comment by bmc-msft** [comment]
While python [Pythonfuzz](https://pypi.org/project/pythonfuzz/) gathers coverage for status output, it does use the coverage to  perform coverage-guided fuzzing, reducing it's efficacy.  As an alternative, [python-afl](https://pypi.org/project/python-afl/) provides a Cython extension to enable coverage guided fuzzing using `afl-fuzz`.

**Comment by stishkin** [comment]
Having fuzzing Python and Java as targets are not currently in our road map.
But we happily accept any contributions to enable those scenarios.
