### ISSUE TITLE
Suggestion: public roadmap

### ISSUE THREAD

**Issue by elee** [microsoft/onefuzz#270]
For teams interested in using OneFuzz understanding what upcoming features or bug fixes will be addressed and when would be helpful context for evaluating the tool and provide transparency about the priorities of the community.

Some good examples:

[GitHub Public Roadmap](https://github.com/github/roadmap/projects/1) 
[AWS containers roadmap](https://github.com/aws/containers-roadmap/projects/1)

**Comment by bmc-msft** [comment]
Good idea.

As a first shot, this is now available.  Upcoming efforts are in sorted based on order of priority.

https://github.com/microsoft/onefuzz/projects/1
