### ISSUE TITLE
Warn users when a non-`setup` DLL is loaded and matches a `setup` DLL

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#2737]
On Windows, we run a LibFuzzer `-help=1` check with loader snaps enabled, to help debug missing DLLs.

Another failure mode is that the user has shipped a targeted DLL in the `setup` container, but a _different_ DLL with the _same name_ gets loaded from a higher-priority location, instead. Detect this, and log a user-facing warning to help future debugging.

Note that this could be built on top of #2736. If we retain the entire loader snap transcript, we can parse all dynamically-linked DLL resolutions, and consequently diff against an enumeration of DLLs in the setup container.

AB#36072

**Comment by mgreisen** [comment]
test comment

**Comment by Porges** [comment]
The support that we've added for `.local` files mitigates this somewhat. We will now _always_ prefer loading DLLs from the executable directory rather than elsewhere.
