### ISSUE TITLE
Add auth callback endpoint

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#2783]
Some teams are creating work items with the following link format: 
`https://{instance_url}/api/download?container={container_name}&filename={file_name}`

However, this fails to authenticate because we don't have an endpoint for completing the authentication flow. The expected endpoint should be: `https://{instance_url}/.auth/login/aad/callback`

By implementing the endpoint and completing the auth flow, links like the one above should work.

AB#36082

**Comment by Porges** [comment]
We do seem to have _something_ enabled because we're getting 500s back from that URI, but there's nothing in the exception log. It's possible this is being (or attempted to be) handled at a higher level in the Azure Functions stack.

**Comment by mgreisen** [comment]
This problem resolved when the customers enabled their vpn.
