### ISSUE TITLE
Allow processing many files in one `coverage` example invocation

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#2825]
Support use of an argv placeholder and directory of inputs, instead of just single command invocations.

AB#43317992

**Comment by stishkin** [comment]
@ranweiler  - are you planning on fixing this ? or is it for future ? 
will this affect user facing commands ? or is it an "internal" improvement ?

**Comment by ranweiler** [comment]
@stishkin, it is internal / not OneFuzz-impacting (implied by ["examples"](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples) in the title).

Closed by #2853.
