### ISSUE TITLE
Deployment section of Getting Started guide is out of date

### ISSUE THREAD

**Issue by jotaylo** [microsoft/onefuzz#2915]
The deployment steps don't give any guidance on how to generate the client_id code for the config file.

I was able to get a deployment set up in release 6.3.0 by adding the --auto_create_cli_app flag to the deploy.py arguments, but with the refactoring for the config file for 6.4.0 the same command fails with:
"Exception: CLI client_id not provided as valid key. Please Provide Valid Config."

[AB#36144](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/36144)

**Comment by AdamL-Microsoft** [comment]
The documentation might need to be updated to clear up confusion on this, but I think that the behavior you see here is unexpected, and this is actually a bug in the config refactoring. 

The intention is that you should be able to start a new deploy while passing the ` --auto_create_cli_app` flag _**while**_ using a config file that doesn't already have the not-yet-created CLI app ID key + value.
