### ISSUE TITLE
Task logger seem to stop before the task is completed

### ISSUE THREAD

**Issue by chkeita** [microsoft/onefuzz#2918]
The log files of some tasks are incomplete. the traces are no longer be redirected after some time. 
It is highly likely that the task logger stops before the task completes

[AB#36155](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/36155)

**Comment by jagunter** [comment]
Relevant task and machine ids where this was observed on OneFuzz instance:

```
| where customDimensions.task_id == 'ed91d341-9f54-453f-920e-bb7d7c04099d'
| where customDimensions.machine_id == '401d74c5-f597-4efd-9594-c6eb7e6b12eb'
```
