### ISSUE TITLE
Prerequisite task failure declared but not observed

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#2922]
## Information

- Onefuzz version: 6.4.0
- OS: Windows

## Provide detailed reproduction steps (if any)

This does not something that reproduces 100% of the time but is something we have observed in some of our jobs. We have a job with two tasks, one which is a prereq for the other. From the failure sample:

```
        "job_id": "67a85fea-802f-41e7-bf5d-21a4244556f3",
        "os": "windows",
        "state": "stopped", (no error)
        "task_id": "73336006-688b-4c46-8f27-67c5aadb4bb0",
```

```
       "config": {
            "prereq_tasks": [
                "73336006-688b-4c46-8f27-67c5aadb4bb0"
            ],
        },
        "error": {
            "code": "TASK_FAILED",
            "errors": [
                "prerequisite task failed.  task_id:d7b2555f-91dd-429f-989e-d6ea03bcc70b"
            ]
        },
        "job_id": "67a85fea-802f-41e7-bf5d-21a4244556f3",
        "os": "windows",
        "state": "stopped",
        "task_id": "d7b2555f-91dd-429f-989e-d6ea03bcc70b",
```

### Expected result

1. The task with the prereq failure error would point to a task in `prereq_tasks`
2. Some other task in the job has failed

### Actual result

1. The prereq failure appears to be pointing to itself for the task failure
2. No other task in the job has failed.

[AB#36164](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/36164)

**Comment by jagunter** [comment]
The last log entry for the failed task don't seem to indicate anything is wrong:

```
[2023-03-03 02:04:26.236115300 UTC] WARN: no new candidate inputs found, sleeping
[2023-03-03 02:04:42.250448800 UTC] WARN: no new candidate inputs found, sleeping
[2023-03-03 02:04:55.263618200 UTC] WARN: no new candidate inputs found, sleeping
[2023-03-03 02:05:12.275660300 UTC] WARN: no new candidate inputs found, sleeping
[2023-03-03 02:05:24.280993300 UTC] WARN: no new candidate inputs found, sleeping
[2023-03-03 02:05:43.291995400 UTC] WARN: no new candidate inputs found, sleeping
[2023-03-03 02:05:54.307858200 UTC] WARN: no new candidate inputs found, sleeping
[2023-03-03 02:06:10.323672 UTC] WARN: no new candidate inputs found, sleeping
[2023-03-03 02:06:26.333586300 UTC] WARN: no new candidate inputs found, sleeping
```

Though it does stop just a little bit before the scheduled end time:

```
        "end_time": "2023-03-03 02:08:31.961340+00:00",
```

Comparing to the task without any reported errors, its last log message is timestamped `2023-03-03T02:06:05.64Z`.

So as far as I can tell everything appears normal other than the reported failure. Is it possible the scheduled task shutdown is being detected as a failure?

**Comment by mgreisen** [comment]
It looks like we shutdown the task at the end of the run time we use this status message and it's not accurate. We think the message is coming from the service, not the task itself.
