### ISSUE TITLE
Logs received by job monitor during deployment may be incomplete

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#2923]
## Information

- Onefuzz version: 6.4.0
- OS: Windows

```
DEBUG:onefuzz:get task: 3d158820-fc7d-41ea-aac5-e29402312bd2
DEBUG:onefuzz:get job: 7f1eea56-5548-4eec-a6e8-daf27ddcca18
```

## Provide detailed reproduction steps (if any)

1. Launch a job with `wait_for_running=True`
2. Write a large amount output from the target executable in the task. In our example we measured 145 lines from a generic supervisor executable.
3. Trigger a failure via failure exit code. In our case we had a Rust binary which panicked.

### Expected result

The output reported by the job monitor would contain the last messages from the binary. In particular we're interested in the Rust panic message in this case.

### Actual result

The output reported by the job monitor does not contain the last several messages from the binary. This behavior has also been observed in the logs received from web hooks.

Checking in Application Insights and the logs there are complete, i.e. I can see the panic message that was produced by the binary.

[AB#36166](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/36166)

**Comment by chkeita** [comment]
This should be fixed in #2896
