### ISSUE TITLE
Azure Compute Gallery support no longer exists in the .NET release

### ISSUE THREAD

**Issue by puhley** [microsoft/onefuzz#2927]
## Information

- Onefuzz version: 6.4.0
- OS: Linux

## Provide detailed reproduction steps (if any)

The new OneFuzz .NET API does not properly handle Azure Compute Galleries. This is similar to an issue previously reported in the Python version of the API: https://github.com/microsoft/onefuzz/issues/1443

1. Specify a path to a compute gallery image in the instance config `default_linux_vm_image` setting. The issue will also occur if the image is specified using "--image" parameter when executing the `onefuzz create scalesets` command.

   The path provided is the Resource ID from the image definition's properties as defined by Azure. The format of the path is:

`/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/{RESOURCE_GROUP}/providers/Microsoft.Compute/galleries/{GALLERY_NAME}/images/{IMAGE_NAME}/versions/{IMAGE_VERSION}`

The IMAGE_NAME is the name of the image (e.g. Custom_Ubuntu)
The IMAGE_VERSION is the specific version (e.g. 1.2.3)

2. Executing a `onefuzz scalesets create` command with a compute gallery image will result in a `creation_failed` state.  The following error message will be returned:

```
    {
        "ephemeral_os_disks": false,
        "error": {
            "code": "INVALID_IMAGE",
            "errors": [
 "Azure.RequestFailedException: The Resource 'Microsoft.Compute/images/{IMAGE_VERSION}' under resource group 'RESOURCE_GROUP' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\r\nStatus: 404 (Not Found)\r\nErrorCode: ResourceNotFound\r\n\r\nContent:\r\n{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Compute/images/{IMAGE_VERSION}' under resource group 'RESOURCE_GROUP' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"}}\r\n\r\nHeaders:\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nx-ms-failure-cause: REDACTED\r\nx-ms-request-id: cd624acf-6361-446d-9829-5766e7c67210\r\nx-ms-correlation-request-id: REDACTED\r\nx-ms-routing-request-id: REDACTED\r\nStrict-Transport-Security: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nDate: Thu, 16 Mar 2023 12:40:27 GMT\r\nContent-Type: application/json; charset=utf-8\r\nExpires: -1\r\nContent-Length: 214\r\n\r\n   at Azure.ResourceManager.Compute.ImageCollection.GetAsync(String imageName, String expand, CancellationToken cancellationToken)\r\n   at Microsoft.OneFuzz.Service.ImageOperations.GetOsInternal(Region region, String image) in /home/runner/work/onefuzz/onefuzz/src/ApiService/ApiService/onefuzzlib/ImageOperations.cs:line 140"
        ]
    },
    "image": "/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/{RESOURCE_GROUP}/providers/Microsoft.Compute/galleries/{GALLERY_NAME}/images/{IMAGE_NAME}/versions/{IMAGE_VERSION}"
    ...
    "state": "creation_failed",
```

### Expected result

It should find the image provided by the Azure Compute Gallery Resource ID path.

### Actual result

The scaleset creation attempt fails and the aforementioned error message is produced.

### Other relevant information
  * I have confirmed that the app has Reader permission to the resource group, gallery, and the image.
  * I tried dropping the version information from the end of the Resource ID, and that did not solve the issue. It will result in the same error message, except rather than the message citing 'Microsoft.Compute/images/{IMAGE_VERSION}', it instead cites, 'Microsoft.Compute/images/{IMAGE_NAME}'.
  * The error message will always cite the resource group of the onefuzz instance even when the compute gallery image is in another resource group. I tried creating an compute gallery within the same resource group as onefuzz, but that did not solve the issue.

[AB#45315](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/45315)

**Comment by puhley** [comment]
As a side note: One thing that I noticed in the code while researching this issue is that you are using the method GetImages(): https://github.com/microsoft/onefuzz/blob/main/src/ApiService/ApiService/onefuzzlib/ImageOperations.cs#L81 

GetImages was supported in ResourceManager.Compute until version 1.0.0-beta.8. However, in version version 1.0.0-beta.9 their change log indicates that they had to, "Rename plenty of classes and property names according to the architecture board's review.".  https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.Compute_1.1.0/sdk/compute/Azure.ResourceManager.Compute/CHANGELOG.md 

As a result, the method was removed in a July 8th commit to, " Resolve arch board comments in compute #29690"
https://github.com/Azure/azure-sdk-for-net/pull/29690/files#diff-f2db620d8651fe4c1997d557bc63c7c5ec1b14e4b699764d444073f4d5bdae25

Therefore, as a future "To Do", you might want to create a related bug to migrate this code to the new method names.

**Comment by puhley** [comment]
With regards to the actual issue that I reported, the code in ImageOperations.cs where the error occurs is a little confusing because there appears to be more than one bug.

I did some local testing on my side. The code starts with checking to see if the resource type is "galleries". https://github.com/microsoft/onefuzz/blob/main/src/ApiService/ApiService/onefuzzlib/ImageOperations.cs#L52
`if (string.Equals(parsed.Id.ResourceType, "galleries", StringComparison.OrdinalIgnoreCase)) {`

However, the ResourceType for a gallery is, 'Microsoft.Compute/galleries'.  Therefore, doing an "equals" comparison on "galleries" will never match. The ResourceType for an image is "Microsoft.Compute/galleries/images" and the ResourceType for a version of an image is, "Microsoft.Compute/galleries/images/versions". In my testing, the images ResourceType, without the version information, works with the loop based search approach at line 60. Specifying a specific version in the gallery Resource ID is not compatible with line 60.

Assuming that the if statement is fixed, then there appears to be another issue where the parsed Resource ID is treated as both a gallery and an image. It is assumed to be a gallery at Line 56 where parsed.Data.Name is assumed to be the name of the gallery. https://github.com/microsoft/onefuzz/blob/main/src/ApiService/ApiService/onefuzzlib/ImageOperations.cs#L56

In the next line, when searching for the image, the parsed.id value is assumed to be the name of the image within the gallery. 
https://github.com/microsoft/onefuzz/blob/main/src/ApiService/ApiService/onefuzzlib/ImageOperations.cs#L60

The parsed variable can not represent both a gallery and an image. Therefore, the code appears to have a second issue where the parsed variable is assumed to be two different resource types.

If the image parameter matches the ResourceType of "Microsoft.Compute/galleries/images", then the code will have the correct parsed.id value when searching for the image.  Prior to searching for the image, the gallery name would need to be extracted out of the Resource ID so that it can be used to identify the correct gallery at line 56. 

Overall, this section of code appears to work if the following is true:
  1) The image reference is of the ResourceType is "Microsoft.Compute/galleries/images" and the image path does not include the version. The Equals comparison in the If statement needs to check for that string.
  2) There is code to extract the gallery name from the image path and the gallery name is then used to identify the gallery instead of using parsed.Data.Name at line 56.

This will result in the "name" variable having the value of "linux" which I believe is in the intent.

Although, the problem with the above approach is that it would require users to provide a ResourceID of a specific image without specifying the version. Typically, the version is important. Therefore, it may be necessary to add a step zero where the version information is removed from the image path prior to processing. This would allow users to specify a version of an image while also allowing this section of code to work one layer higher at the image level.

**Comment by Porges** [comment]
I have a PR #2369 to rework the way we parse and handle images, and it's possible that this will address the problem. I will take a look and try to validate the scenario you've posted here.

**Comment by puhley** [comment]
Your pull request completely removes the file in question. Therefore, I assumes that it will fix the issue. I'll keep an eye on the project for when your changes get merged. Thanks for the update!

**Comment by Porges** [comment]
I’ve verified that with my PR I can create scalesets with both versioned and non-versioned image references to gallery images. We’ll look to get this change into the next release.
