### ISSUE TITLE
regression_reported webhook JSON blob is missing fields in regression_report object

### ISSUE THREAD

**Issue by stishkin** [microsoft/onefuzz#2939]
Seems like this is a bug on OneFuzz side:
Here is a snippet from one of the regression reported Webhooks. 
Regression Report is not correctly populated. Meanwhile original_crash_test_result has all values set

{
    "eventType": "regression_reported",
    "subject": "fuzzingprod01",
    "data": {
      "regression_report": {
        "crash_test_result": {
          "crash_report": null,
          "no_repro_report": null
        },
        "original_crash_test_result": {
          "crash_report": {
            "input_url": null,
            "input_blob": {
              "account": "fuzzz",
              "container"": ""oft-crashes-e008f78a57295d909934fb3b86c390ca",
              "name": "oom-bf8cfae4a8a619e7df22d4d61a69b32d2fcea885"
            },
            "executable": "C:\\onefuzz\\blob-containers\\fuzzpremium01\\fuzzzer.exe"

[AB#45331](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/45331)

**Comment by chkeita** [comment]
No repro in the last 30 days
