### ISSUE TITLE
AFLplusplus Support

### ISSUE THREAD

**Issue by domenukk** [microsoft/onefuzz#3]
Great project!
As development on afl itself doesn't seem to be high priority anymore, it would be nice to see out of the box support for additional afl-based fuzzers, such as afl++.

**Comment by bmc-msft** [comment]
User-provided custom fuzzers is a first-class supported feature.  We have a few examples, including [honggfuzz](https://github.com/microsoft/onefuzz/blob/main/src/cli/examples/honggfuzz.py), [domato](https://github.com/microsoft/onefuzz/blob/main/src/cli/examples/domato.py), and even [compiling an libfuzzer targets from oss-fuzz integrated projects](https://github.com/microsoft/onefuzz/blob/main/src/cli/examples/oss-fuzz-target.py).

That said, including support for AFL++ as a built-in path should be straight forwards.

Given the large number of ongoing research efforts based on AFL, we should make it stream-lined to let users pick from an arbitrary set of AFL implementations, including making it easy to add new builds, versions, or forks of AFL.
