### ISSUE TITLE
why can't find unique reports

### ISSUE THREAD

**Issue by log-e** [microsoft/onefuzz#31]
## Information

- Onefuzz version: 1.0
- OS: ubuntu20.04

## Provide detailed reproduction steps (if any)

![Xnip2020-09-24_14-06-54](https://user-images.githubusercontent.com/31824303/94107101-5d65d080-fe6f-11ea-9740-9bcf3dfb60db.jpg)

![image](https://user-images.githubusercontent.com/31824303/94107157-75d5eb00-fe6f-11ea-99e9-07459e3deaec.png)

### Expected result

it should existed unique_report.json

### Actual result
i can not find the unique_report.json , it just a empty array

**Comment by bmc-msft** [comment]
There are a few reasons why this could be the case.

1) the crashes are unreliable.  The crash reporting tasks support retrying suspected crashing inputs a configurable number of time.   In the libfuzzer basic template, this is exposed via the  `--check_retry_count N` argument.  

    As as you have a no-repro container without files, I suspect this isn't the case.
2) The crash reporting task did not start or had errors.

For the later, this how I debug those issues:

1. List the details of the libfuzzer crash reporting tasks.
   `onefuzz tasks list --job_id JOB_ID --state --query "[?config.task.type == 'libfuzzer_crash_report']"`

    (Note: by default, `onefuzz tasks list` only returns tasks in the states indicating it's either scheduled or currently running.  The `--state` argument without values indicates ignore the list of states)
2. If this does not highlight issues, I recommend searching your App Insights instance for the `task_id` returned from the above `onefuzz tasks list` command.

**Comment by ayooosh22gamdi** [comment]
> 
> 
> 
> 
> 
> 
> ## Information
> 
> 
> 
> - Onefuzz version: 1.0
> 
> - OS: ubuntu20.04
> 
> 
> 
> ## Provide detailed reproduction steps (if any)
> 
> 
> 
> ![Xnip2020-09-24_14-06-54](https://user-images.githubusercontent.com/31824303/94107101-5d65d080-fe6f-11ea-9740-9bcf3dfb60db.jpg)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/31824303/94107157-75d5eb00-fe6f-11ea-99e9-07459e3deaec.png)
> 
> 
> 
> ### Expected result
> 
> 
> 
> it should existed unique_report.json
> 
> 
> 
> ### Actual result
> 
> i can not find the unique_report.json , it just a empty array
> 
> 
> 
>

**Comment by ranweiler** [comment]
_(Removed an apparent spam comment that just quoted the issue body)_

**Comment by anban-wuxing** [comment]
> There are a few reasons why this could be the case.
> 
> 1. the crashes are unreliable.  The crash reporting tasks support retrying suspected crashing inputs a configurable number of time.   In the libfuzzer basic template, this is exposed via the  `--check_retry_count N` argument.
>    As as you have a no-repro container without files, I suspect this isn't the case.
> 2. The crash reporting task did not start or had errors.
> 
> For the later, this how I debug those issues:
> 
> 1. List the details of the libfuzzer crash reporting tasks.
>    `onefuzz tasks list --job_id JOB_ID --state --query "[?config.task.type == 'libfuzzer_crash_report']"`
>    (Note: by default, `onefuzz tasks list` only returns tasks in the states indicating it's either scheduled or currently running.  The `--state` argument without values indicates ignore the list of states)
> 2. If this does not highlight issues, I recommend searching your App Insights instance for the `task_id` returned from the above `onefuzz tasks list` command.



> There are a few reasons why this could be the case.
> 
> 1. the crashes are unreliable.  The crash reporting tasks support retrying suspected crashing inputs a configurable number of time.   In the libfuzzer basic template, this is exposed via the  `--check_retry_count N` argument.
>    As as you have a no-repro container without files, I suspect this isn't the case.
> 2. The crash reporting task did not start or had errors.
> 
> For the later, this how I debug those issues:
> 
> 1. List the details of the libfuzzer crash reporting tasks.
>    `onefuzz tasks list --job_id JOB_ID --state --query "[?config.task.type == 'libfuzzer_crash_report']"`
>    (Note: by default, `onefuzz tasks list` only returns tasks in the states indicating it's either scheduled or currently running.  The `--state` argument without values indicates ignore the list of states)
> 2. If this does not highlight issues, I recommend searching your App Insights instance for the `task_id` returned from the above `onefuzz tasks list` command.

thank your reply, i create 2 vms on azure, the libfuzzer_crash_report task state is scheduled, not running, is it the reason?
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/64947813/94353783-b4ee8100-00a7-11eb-868a-daf4439385ce.png">

**Comment by log-e** [comment]
hi, i try to create pools with 2 vms on west us azure, it works,i can find all 8 unique reports now. thank your woks,this project is really cool.

**Comment by JsHuang** [comment]
I have the same issue and I found all my tasks were in waitting or scheduling state, why? @bmc-msft

**Comment by bmc-msft** [comment]
@log-e, your assumption was correct.  By default, the libfuzzer template creates 2 VMs for fuzzing.  If your pool has only 2 VMs, both will be allocated for fuzzing and none for the other tasks in the job.
