### ISSUE TITLE
onefuzz template libfuzzer qemu_user is missing readonly_inputs parameter

### ISSUE THREAD

**Issue by stishkin** [microsoft/onefuzz#3115]
readonly_templates  need to be added to OneFuzz CLI for qemu_user template

[AB#152296](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/152296)

**Comment by chkeita** [comment]
Here is the list of all the parameters present in the basic template but not in the qemu_user template:
- analyzer_env
- analyzer_exe
- analyzer_options
- check_retry_count
- colocate_secondary_tasks
- crash_report_timeout
- crashes
- dryrun
- expect_crash_on_failure
- extra_container
- extra_files
- minimized_stack_depth
- module_allowlist
- notification_config
- readonly_inputs
- setup_dir
- source_allowlist
- target_timeout
- target_workers
- tools
- vm_count

**Comment by Porges** [comment]
> Here is the list of all the parameters present in the basic template but not in the qemu_user template:

Just to put an external comment about this: `qemu_user` is still considered experimental so we won't be investing a lot of effort into bringing up to parity with the `libfuzzer` templates.
