### ISSUE TITLE
Allow expensive coverage module analysis once, and reuse it

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#3178]
For a given run of the `coverage` task, introduce an in-memory module disassembly cache, and reuse it allow the amortization of expensive analyses. Also, consider enabling a separate timeout for the first input test case, and/or seeding the cache with the target and all allowlist-included library dependencies.

Context: the `coverage` task re-analyzes loaded modules for each tested input. Usually this is fine. When there are many, many functions that are included by a given allowlist, this can cause timeouts. In practice, we want to accept very expensive _one-time_ per-module analyses that get amortized over many inputs.

- [x] Core caching support: https://github.com/microsoft/onefuzz/issues/3216
- [x] Eager use in `onefuzz-task`: https://github.com/microsoft/onefuzz/issues/3217

[#AB152691](https://fuzzfest.visualstudio.com/Onefuzz/_workitems/edit/152691)

**Comment by stishkin** [comment]
@ranweiler  is this work you planning to do ? Or is this future optimization suggestion ?

**Comment by ranweiler** [comment]
> @ranweiler is this work you planning to do ? Or is this future optimization suggestion ?

Answered offline. I can help by implementing the underlying caching mechanism in the `coverage` crate, when the team picks this up, but someone else will need to drive the actual OneFuzz work.

**Comment by ranweiler** [comment]
Closed by @tevoinea via #3216, #3217.
