### ISSUE TITLE
Unable to deploy first instance of Onefuzz.

### ISSUE THREAD

**Issue by Ashutosh-18-hub** [microsoft/onefuzz#3232]
## Information

- Onefuzz version: 8.3.0
- OS: 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

## Provide detailed reproduction steps (if any)

1. python3 ./deploy.py centralindia onefuzzresource onefuzzinstance ashutosh.pandey@mavenir.com config.json
2.
3.

### Expected result

_What is the expected result of the above steps?_

### Actual result

Getting this below error:-

Error while attempting to retrieve the latest Bicep version: HTTPSConnectionPool(host='aka.ms', port=443): Max retries exceeded with url: /BicepLatestRelease (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)'))).
Error while attempting to retrieve the latest Bicep version: HTTPSConnectionPool(host='aka.ms', port=443): Max retries exceeded with url: /BicepLatestRelease (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)'))).
INFO:deploy:parsing config: config.json
Traceback (most recent call last):
  File "./deploy.py", line 1399, in <module>
    main()
  File "./deploy.py", line 1393, in main
    state[1](client)
  File "./deploy.py", line 246, in check_region
    with open(self.arm_template, "r") as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'azuredeploy-bicep.json'

[AB#156491](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/156491)

**Comment by nharper285** [comment]
Hi @Ashutosh-18-hub, are you running the deploy script from within the deployment zip? It appears the bicep.json file that's included in the deployment zip is not present in the directory that you're running the script from.
