### ISSUE TITLE
[CLI] Incorrectly-set AZCOPY env variable causes confusing errors

### ISSUE THREAD

**Issue by Porges** [microsoft/onefuzz#3234]
If the `AZCOPY` environment variable is set to a directory containing the AzCopy executable instead of the executable itself, then the CLI produces the error:

```console
ERROR:cli:command failed: 13 Access is denied None 5 None
```

This is confusing and not helpful. I propose that if the `AZCOPY` variable is set to a directory, then we look in that directory for the executable.

[AB#156895](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/156895)

**Comment by kananb** [comment]
https://github.com/microsoft/onefuzz/pull/3344
