### ISSUE TITLE
Wrong error message when job doesn't exist

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#3276]
## Information

- Onefuzz version: 8.4
- OS: N.A

## Provide detailed reproduction steps (if any)

1. `onefuzz jobs get {invalid job id}

```
.\onefuzz-cli-8.4.0.exe jobs get 8b0a2196-fb86-6a47-4412-4df9c249485d
ERROR:cli:command failed: request did not succeed (400: INVALID_TASK): no such job
```

It says INVALID_TASK when the job doesn't exist.

### Expected result

_What is the expected result of the above steps?_

It should say INVALID_JOB

[AB#160428](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/160428)

**Comment by kananb** [comment]
https://github.com/microsoft/onefuzz/pull/3318
