### ISSUE TITLE
`get_files` in the CLI needs to support regression reports

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#3338]
## Information

- Onefuzz version: 8.5.0
- OS: N/A

## Provide detailed reproduction steps (if any)

1. Execute `onefuzz repro get_files` on a regression report

```
*snip*
ERROR:cli:traceback: Traceback (most recent call last):
ERROR:cli:traceback:   File "onefuzz\cli.py", line 602, in execute_api
ERROR:cli:traceback:   File "onefuzz\cli.py", line 77, in call_func
ERROR:cli:traceback:   File "onefuzz\api.py", line 562, in get_files
ERROR:cli:traceback: KeyError: 'input_blob'
ERROR:cli:traceback:
ERROR:cli:command failed: input_blob
```

[AB#162907](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/162907)

**Comment by kananb** [comment]
https://github.com/microsoft/onefuzz/pull/3340
