### ISSUE TITLE
Add a "check for duplicate" field in the notification config

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#3384]
ADO orgs can use custom fields to track when a work item is marked as duplicate. We should add a new property in our notification config where users can specify a set of fields and values which indicate a work item has been marked as duplicate. These keys/values may be specific to a user's ADO org.

Example:

```jsonc
{
    // If any of the key/value pairs match, the work item will be considered as 'marked as duplicate'
    "ado_duplicate_fields": {
        // Example for a default ADO org
        "System.Reason": "Duplicate",
        "Microsoft.VSTS.Common.ResolvedReason": "Duplicate",
        "My.Super.Custom.Field": "MySuperCustomValue"
    }
}
```

Also, don't forget to update the docs!

[AB#163793](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/163793)

**Comment by tevoinea** [comment]
We should also consider the case when the duplicate is set via work item relationships (ex: `DuplicateOf`). We support the 'default' relationships in ADO, I'm not sure if it's possible to add custom relationships but if it is, we should support it.

**Comment by kananb** [comment]
> We should also consider the case when the duplicate is set via work item relationships (ex: `DuplicateOf`). We support the 'default' relationships in ADO, I'm not sure if it's possible to add custom relationships but if it is, we should support it.

Assuming that[ this page on work item links](https://learn.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops) is comprehensive, it doesn't look like there's support for custom relationships.
Not unless it's [self-hosted to some extent](https://learn.microsoft.com/en-us/previous-versions/azure/devops/reference/xml/define-custom-link-type?view=tfs-2017), but this seems pretty niche. Maybe I'm wrong?

**Comment by tevoinea** [comment]
> > We should also consider the case when the duplicate is set via work item relationships (ex: `DuplicateOf`). We support the 'default' relationships in ADO, I'm not sure if it's possible to add custom relationships but if it is, we should support it.
> 
> Assuming that[ this page on work item links](https://learn.microsoft.com/en-us/azure/devops/boards/queries/link-type-reference?view=azure-devops) is comprehensive, it doesn't look like there's support for custom relationships. Not unless it's [self-hosted to some extent](https://learn.microsoft.com/en-us/previous-versions/azure/devops/reference/xml/define-custom-link-type?view=tfs-2017), but this seems pretty niche. Maybe I'm wrong?

Ah you're probably right, I thought (incorrectly) that the Microsoft.VSTS.* fields were custom.
