### ISSUE TITLE
Excessive commenting on OneFuzz bugs

### ISSUE THREAD

**Issue by AdamL-Microsoft** [microsoft/onefuzz#3413]
## Information

- Onefuzz version: 8.6.3 (maybe originating from 8.6.2 or earlier too)

We're seeing some reports of bugs that have a flood of repeating comments from the same job and duplicate crashing inputs, in one case so far there are 1000+ comments on the same bug.

example from a bug with over 1000 comments from the OneFuzz service:
![image](https://github.com/microsoft/onefuzz/assets/103067949/491b03aa-5a97-40ba-a13d-4b53bc7bf88b)

[AB#164517](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/164517)

**Comment by stishkin** [comment]
resolved, not an issue
