### ISSUE TITLE
Add `AdditionalInfo` property to report

### ISSUE THREAD

**Issue by tevoinea** [microsoft/onefuzz#3471]
For teams that create their own crash reports, they would like to have additional properties to use in their notification templates.

We can add an `Dictionary<string, string> AdditionalInfo` to the `Report` object.
https://github.com/microsoft/onefuzz/blob/d99960323de7336e0463f92babb80ebc841fa627/src/ApiService/ApiService/OneFuzzTypes/Model.cs#L489-L513

Then in a notification template, someone could reference is by doing something like `report.additional_info.my_custom_field`

[AB#164905](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/164905)

**Comment by DrChat** [comment]
To further inform the implementation, we are looking to add additional fields that correspond to URLs for `extra-outputs` artifacts we produce from our analyzer task.
We can generate the download URLs ourselves for these artifacts and add them as `additional_info` fields, but if they were made explicit then perhaps your agent could add metadata such as error information if the upload failed (for instance).

**Comment by tevoinea** [comment]
Closing because this already exists as `ExtensionData`
