### ISSUE TITLE
Update message when downloading logs

### ISSUE THREAD

**Issue by mgreisen** [microsoft/onefuzz#3490]
## Information

- Onefuzz version: 8.8
- OS: n/a

## Provide detailed reproduction steps (if any)

1. download the logs using the command "onefuzz debug logs get --job_id xxxx"

The statement that is returned to the console is:
"INFO:onefuzz:Downloading only the 1 most recent files"

It is unclear that is the most recent file for each task. 

Using alternate phrasing easily clears this up by adding "for each task" to the end. 

[AB#165341](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/165341)

**Comment by stishkin** [comment]
There is no "most recent" anymore, since we should be downloading "all" logs by default

**Comment by kananb** [comment]
From what I understand, unless the `--all` flag is used only the `--last n` most recent logs are downloaded where `n` defaults to `1`.
