### ISSUE TITLE
Failed job template submission should not result in "zombie" jobs 

### ISSUE THREAD

**Issue by stishkin** [microsoft/onefuzz#3563]
Right now if azcopy fails during job submission - the OneFuzz CLI creates a "zombie" job and returns az copy stderr as error.

OneFuzz CLI should not create zombie jobs

[AB#167576](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/167576)

**Comment by chkeita** [comment]
az_copy already has an internal mechanism for rertying on network errors, timeouts and server errors. 
https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-configure#log-and-plan-files

**Comment by chkeita** [comment]
Renaming this to focus on no having zombie jobs instead of having a retry logic on top of az_copy
