### ISSUE TITLE
Capture stdout/stderr of the applications under test

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#370]
Right now, we do not capture the stdout or stderr or the applications under test.  This makes debugging issues with the application difficult. 

AB#39994716

**Comment by bmc-msft** [comment]
On linux, `pete` 0.4.0 moves away from a private `Command` to using `std::process::Command`, which means we can now use `std::process::Stdio`.

The change makes a few other things, like the custom kill on drop wrapper less ergonomic.

**Comment by bmc-msft** [comment]
@ranweiler Can you take a look at this?

**Comment by chkeita** [comment]
addressed in #400
