### ISSUE TITLE
new_unique_report and new_report CustomEvents in Application Insights unexpectedly equal.

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#413]
## Information

- Onefuzz version: 1.10.0
- OS: Windows 10 RS5-Pro
- Executable: Fuzz.exe (from OneFuzz repo)

## Bug Description 
It appears that the CustomEvents logged in Application Insights for a deployed job are equal in count for new_unique_reports and new_reports. This should not be the case. Unique report events should only be fired when a unique crash is found. Currently, it appears that a unique report event is fired every time a new report event is fired. 

## Provide detailed reproduction steps (if any)
1. Deploy OneFuzz job against sample fuzz.exe via the CLI command: ` .\onefuzz-cli-1.10.0.exe template libfuzzer basic edgTest123 edgTest123 5 EDG-FUZZING --target_exe C:\workspace\onefuzz\onefuzz-samples\windows-libfuzzer\fuzz.exe`
2. Allow job to run and track progress via CLI command: `.\onefuzz-cli-1.10.0.exe status top`. Tracking progress via status top properly indicates that the unique crashes or unique_reports value is a subset of total or new_reports. 
3. Log into the Azure portal and the Application Insights resource of the OneFuzz deployment instance where the job is hosted.
4. Search 'result' in the 'Transaction Search' tab.
5. Click the 'Grouped Results' tab. 
6. Note that the number of 'new_unique_report' custom events **matches** 'new_reports' **exactly.** This appears to indicate that for every new_report event fired, there is a new_unique_report value fired, as well. new_unique_report events should only be fired if the report is unique. 

This behavior was also verified by querying the Application Insights Kusto database directly via Azure Data Explorer.

Image of Application Insights Transaction Search:
<img width="700" alt="Screenshot 2021-01-04 151655" src="https://user-images.githubusercontent.com/74685766/103589285-ea251f00-4e9f-11eb-8368-35fbbc115c85.png">

### Expected result
1. The expected result is that these values would not be equal. new_unique_reports would be a subset of new_reports -- firing only when a unique crash is found. 

### Actual result
1. The event counts are equal.

**Comment by ranweiler** [comment]
Relevant code: 

https://github.com/microsoft/onefuzz/blob/e799eb03cdc22aebd2a16ab9cc141917fae44cff/src/agent/onefuzz-agent/src/tasks/report/crash_report.rs#L61-L79
