### ISSUE TITLE
Auto-Update for Unused VMSS Nodes

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#414]
Hi Team, 

We recently noticed that unused VMSS nodes never undergo an update or re-image. We know, however, that nodes that run tasks are reimaged after all tasks are complete. There are certain security and update requirements required by our organization that are violated when VMSS nodes go without update or reimage for +7 days. 

We are proposing a feature that would automatically reimage nodes once they've gone >7 days without use or update.

**Comment by bmc-msft** [comment]
PR https://github.com/microsoft/onefuzz/pull/416,  is progress towards enabling this feature.   

The next step is to add a timer task that marks automatically marks nodes as "needs to be reimaged upon completing existing work" once a week.
