### ISSUE TITLE
Add ability to set instance wide defaults for bug fields

### ISSUE THREAD

**Issue by jordyn** [microsoft/onefuzz#432]
When using OneFuzz to file bugs in AzDevOps I would like the ability to set instance wide defaults for any bug field. For all fuzzing bugs there is a common set of fields that we always want set and would like to avoid having to duplicate those fields across every job template. 

Ideally a specific job could overwrite the instance defaults when filing bugs but would always default to the instance defaults if not set.
 

AB#39994710

**Comment by bmc-msft** [comment]
Job templates should provide this information already.  That said, exposing a config item of  `Dict[str,/str]` in `instance_config`, then exposing `instance_config` to the job templates might be useful as well.

**Comment by stishkin** [comment]
Not applicable anymore
