### ISSUE TITLE
{target_options} in supervisor_options does not expand to a list

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#438]
### Overview

The `{target_options}` expansion in `supervisor_options` expands to a single string instead of a list of strings as shown in the example in  [command-replacement docs](https://github.com/microsoft/onefuzz/blob/8d77dc325d63b8c1cb206ad7d81dbac4611e425f/docs/command-replacements.md).

### Setup

```
supervisor_options = [
    "{target_exe}",
    "{target_options}",
]

target_options = [
    "a",
    "b",
    "c",
]
```

### Expected

```
supervisor_options = [
    "/path/to/target.exe",
    "a",
    "b",
    "c",
]
```

### Actual

```
supervisor_options = [
    "/path/to/target.exe",
    "a b c",
]
```

### Work-Around

I worked around this issue by inserting the target options directly into the supervisor options instead of using expansion.

```
supervisor_options = [
    "{target_exe},
]
target_options = [
    "a",
    "b",
    "c",
]
supervisor_options.extend(target_options)
```

### Affected Versions

Tested with OneFuzz 1.11 instance and CLI.

**Comment by bmc-msft** [comment]
We probably should keep the existing implementation as is and update the documentation to match reality and provide an additional mechanism to provide a flattened list.

Considering these are used to construct the `argv` for the underlying execv call for the supervisor, `['a b c']` and `['a', 'b', 'c']` can have very different behaviors.

**Comment by bmc-msft** [comment]
Re-thinking this, I think adding the functionality to recursively expand nested lists is going to add more problems than it solves.  

I've submitted a PR that corrects the documentation to demonstrate how it works in practice and includes a suggested work-around akin to OP's example.

@jagunter do you have any comments on the PR?

**Comment by bmc-msft** [comment]
I've unlinked the PR to this issue for now, as the documentation should be updated regardless of potentially enabling a flattened list expansion.
