### ISSUE TITLE
Generic fuzzing task type

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#439]
The only generic fuzzing tasks currently available are:

* generic_supervisor
* generic_generator

Both of these task types assume there are at least 2 executables: a fuzzing framework executable and the target executable. However there is not a generic task that accepts a single target executable with the fuzzing framework integrated therein (similar to LibFuzzer).

This limitation can be worked around by creating a shim executable that simply executes the target with the provided options. This shim can be uploaded to the tools container and used as the `supervisor_exe` in a generic supervisor task. However it requires additional setup and maintenance of a shim exe specifically for using the fuzzer in onefuzz, which isn't ideal.

**Comment by bmc-msft** [comment]
PR #454 is the first of multiple PRs to enable this functionality.
