### ISSUE TITLE
enabling "immutable" container configuration

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#452]
Example use case:  I have a set of JPEGs and multiple JPEG parsers.  I'd like to have a shared base corpus of JPEGs that can be used by all of the JPEG parsers, but I don't want a user's fuzzing task to incidentally corrupt the JPEG corpus container.

While we support generating read-only corpus containers, that is only done at the task level.  It would be useful to set the immutability at the Azure Container level.  Azure provides two mechanisms, "time based" and "Legal" holds.

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-immutable-storage 

AB#39994708

**Comment by stishkin** [comment]
Closing for now. If feature is needed, new item will be opened
