### ISSUE TITLE
Tasks stuck in "waiting" or "scheduled"

### ISSUE THREAD

**Issue by T-S-A** [microsoft/onefuzz#467]
## Information

- Onefuzz version: onefuzz 1.11.0
- OS: 18.04.5 LTS (Bionic Beaver)

## Provide detailed reproduction steps (if any)

After following the setup instructions for Onefuzz, including creating a pool of VMs, we are able to create example jobs, like libfuzzer or AFL, but each task for the jobs are stuck in either "scheduled" or waiting. The jobs never run. We tried deleting all jobs and even creating a new pool of VMs, but no success.

![image](https://user-images.githubusercontent.com/5905885/105856313-b9bc3680-5fae-11eb-92f6-a8a47178f25e.png)

**Comment by bmc-msft** [comment]
There is a known-issue in 1.11.0 that causes idle VMs from not being able to request tasks (PR #459), which is compounded by the dead-node detection was not functioning (PR #458).

These will be fixed in the next release, which I hope to publish today.

**Comment by T-S-A** [comment]
Thanks!

**Comment by bmc-msft** [comment]
@T-S-A , we identified and fixed a bug that would cause a deadlock in the supervisor (PR #603)

With this change combined with the previous issues, I believe this to be corrected.  If you upgrade, you may need to recreate your scalesets to get this change.

**Comment by bmc-msft** [comment]
Please let us know if you continue to have this issue.
