### ISSUE TITLE
Enable fan-in of streaming file updates from multiple storage containers

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#470]
Motivation: the `generic_analysis` task has a monitor queue, which is set to monitor its read-only inputs (currently named `crashes`) container. However, there are cases where we want to fan in file insertions from multiple input containers, and run the same analysis on them as they come in. These inputs aren't necessarily crashes, either.

I think it would be sufficient to change the definition of `generic_analysis` to rename the `crashes` container to something more general like `inputs`, and then change the `compare` constraint to `AtLeast`. We would just need to make sure we initialize and batch process each container, as we do for some libfuzzer tasks. 

AB#39994702

**Comment by bmc-msft** [comment]
From the queuing perspective, the Web API already supports fan-in of multiple containers, though the input containers monitored must all be of the same `ContainerType`.

Seen here:
https://github.com/microsoft/onefuzz/blob/81e3ea98951de53d4b79fc57357d697f3a9c00fb/src/api-service/__app__/onefuzzlib/tasks/config.py#L24-L32

As such, I agree with your assessment that changing `Compare.Equal` to `Compare.AtLeast` is sufficient to support the fan-in.  

However, this would change the context of the container types for the analysis task.  In practice, the container types are added as the `container_type` tag in the Azure Storage Containers.  While we're not validating the container types at the moment, we've discussed doing this previously.

(Impl where the container_type tag is specified when creating containers)
https://github.com/microsoft/onefuzz/blob/81e3ea98951de53d4b79fc57357d697f3a9c00fb/src/cli/onefuzz/templates/__init__.py#L119-L124

**Comment by bmc-msft** [comment]
Note, this is used in the `radamsa` task, which uses generic analysis on Windows targets.  This should be considered, given how the job templates specify containers by container types.

https://github.com/microsoft/onefuzz/blob/81e3ea98951de53d4b79fc57357d697f3a9c00fb/src/cli/onefuzz/templates/radamsa.py#L224-L229

**Comment by bmc-msft** [comment]
Thinking about this more, the `generic_analysis` task at the agent would need to support consuming multiple `crashes` containers.

We run all of the existing content through the analysis tasks via downloading the `crashes` container and processing every entry first, then monitor the queue for any files that get added after the task starts.

**Comment by ranweiler** [comment]
> would need to support consuming multiple crashes containers.

Yep, I was trying to address that when I wrote "we would just need to make sure we initialize and batch process each container [...]" (but LMK if you mean something else). Either way, I agree we would need to update both the task definition and the task implementation in the agent.

**Comment by stishkin** [comment]
Closing for now, since no customer asked for this
