### ISSUE TITLE
No crash report was produced

### ISSUE THREAD

**Issue by Sinderella** [microsoft/onefuzz#492]
## Information

- Onefuzz version: 2.1.0
- OS: Azure console

## Provide detailed reproduction steps (if any)

1. Following [getting started guide](https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md), until the ["Investigating Crashes" section](https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md#investigating-crashes)
2. The only change that I did was the duration of the job, I changed it to 1 hour so that I could understand the workflow.
3. During fuzzing, it reported a number of crashes in `onefuzz status top`.
4. During fuzzing and by the end of the job, I tried to list the unique reports just like the instruction, no json file was returned.

I am not sure if this is expected, but I cannot tell when the report is being generated. I also wonder if there's another better way to finish the job faster than an hour for testing purposes, in case the report is only generated by the end of the duration.

**Comment by chkeita** [comment]
HI @Sinderella 
Can you confirm that the report task was running?  you can see the state of the tasks in the status of the tasks `onefuzz status top`
Can you also check the number of vm in your scaleset. The libfuzzer basic template will consume 4 vms (2 for the fuzzer, 1 for crash report, 1 for coverage). You will need at least that many vms in your scaleset to have all the tasks running at the same time.

**Comment by Sinderella** [comment]
> Can you confirm that the report task was running? you can see the state of the tasks in the status of the tasks `onefuzz status top`

Yes, it was running and showing the number of crashes found.

> Can you also check the number of vm in your scaleset. The libfuzzer basic template will consume 4 vms (2 for the fuzzer, 1 for crash report, 1 for coverage). You will need at least that many vms in your scaleset to have all the tasks running at the same time.

I think this is the issue then, I was testing with only 1 or 2 VMs. Can you please point me out to where I can get the numbers? I always thought that those were containers, not VMs. I will give it another try tomorrow. Thank you!

**Comment by Sinderella** [comment]
Adding the VMs fixed the issue, cheers!

**Comment by chkeita** [comment]
glad to hear that.
You can see the number of vm required for each task in a job by using `onefuzz tasks list --job_id <job_id>`.
The number will be under config.pool.count.

Those values are set for each tasks in the [template](https://github.com/microsoft/onefuzz/blob/main/src/cli/onefuzz/templates/libfuzzer.py).
Note that the libfuzzer basic template allows you to control the number of vm of the [fuzz tasks only](https://github.com/microsoft/onefuzz/blob/02721f3ed9a11901df9ba504c7c1f38e25209475/src/cli/onefuzz/templates/libfuzzer.py#L238) (the coverage and the report tasls are hardcoded to 1).
