### ISSUE TITLE
Proxy VM is not sending heartbeats in certain circumstances

### ISSUE THREAD

**Issue by andrew-slutsky** [microsoft/onefuzz#498]
## Information

- Onefuzz version: 2.1.0
- OS: Windows (CLI)

This happens in our production instance which you may be familiar with c***rod05, but it does not seem to happen on our less busy or newer instances. 

## Provide detailed reproduction steps (if any)

1. Run the 'debug' command 
$ onefuzz.exe debug node rdp <guid>

2. Connect as you would if you wanted to inspect some onefuzz logs on the node

3. Browse the web, watch TV, or just leave the RDP session open

After 10 to 15 minutes you will be disconnected.

4. You can recreate the debug session using the same command in Step 1, and will see the node in the same state it was before you disconnected.

Upon further investigation, the instance activity log shows the App Function (System-Assigned Managed Identity) has deleted the Proxy VM and that App Insights did not log a heartbeat for 10 minutes before deleting the Proxy VM. So partly, the behavior was expected. That is why we think this issue has something to do with the heartbeats. 

### Expected result

We expect the Proxy VM to send heartbeats and then for the App Function to process them so it does not delete the Proxy VM.

 

AB#39994700

**Comment by bmc-msft** [comment]
I can reproduce this.  Investigating.

**Comment by bmc-msft** [comment]
This apparently isn't fixed.  #520 will help debug this further.

**Comment by stishkin** [comment]
No repro

**Comment by stishkin** [comment]
no repro in latest version I meant
