### ISSUE TITLE
expose iterations per second in 'status top'

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#50]
It would be beneficial to expose the 'iterations per second' and '% of coverage' for fuzzing tasks in 'status top' 

AB#39994787

**Comment by bmc-msft** [comment]
While not exposed in `status top`, as of 1.7.0, this information is available via users logged into the Azure CLI.

In the near future, I intend to expose automatically building these queries in the `onefuzz debug` sub-command

## Coverage

```
$ onefuzz debug logs query "customEvents | where name == 'coverage_data' | where customDimensions.job_id == '88ba6efd-03ed-4ee0-82db-141e77859673' | order by timestamp desc | project timestamp, rate=customDimensions.rate | take 1"
{
    "PrimaryResult": [
        {
            "rate": "0.47619047619047616",
            "timestamp": "2020-11-18T00:09:40.793Z"
        }
    ]
}
```

## Iterations per Second
```
$ onefuzz debug logs query "customEvents | where name == 'runtime_stats' | where customDimensions.job_id == '88ba6efd-03ed-4ee0-82db-141e77859673' | where customDimensions.execs_sec > 0 | order by timestamp desc | project timestamp, execs_sec=customDimensions.execs_sec | take 1"
{
    "PrimaryResult": [
        {
            "execs_sec": "191044",
            "timestamp": "2020-11-18T00:08:53.98Z"
        }
    ]
}
```

Note, these are per-VM AND per-worker stats.
* number of VMs used for fuzzing is controlled by `--vm_count`.  This defaults to 2.
* Number of workers for a libfuzzer target within the VM is controlled via `--target_workers`.  This defaults to `max(NUM_CORES-1, 1)`.

**Comment by stishkin** [comment]
Iterations per second is better displayed in a different rendering resource. Like Azure hosted Grafana.
