### ISSUE TITLE
support libFuzzer's __libfuzzer_extra_counters for coverage analysis

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#536]
multiple fuzzers that provide their own coverage instrumentation make use of libfuzzer's feature of `__libfuzzer_extra_counters` to pass map coverage to something libFuzzer can inspect.

* libfuzzer-dotnet https://github.com/Metalnem/libfuzzer-dotnet/blob/543b170a67bdd39e9ba260fe54bc93c77b877c24/libfuzzer-dotnet.cc#L19-L20
* go-fuzz https://github.com/dvyukov/go-fuzz/blob/6a8e9d1f2415cf672ddbe864c2d4092287b33a21/go-fuzz-build/main.go#L851-L864

For libfuzzer-dotnet, this is copied via a shared-memory segment from a secondary process after each `LLVMFuzzerTestOneInput`.

**Comment by bmc-msft** [comment]
Given the changes in coverage, having a more meaningful understanding of coverage for these other coverage utilities would be good, but probably not focused on `extra_counters`.  Instead, I imagine refocusing this work item to address other libfuzzer-like coverage would be useful.

**Comment by ranweiler** [comment]
Made redundant by #2006.
