### ISSUE TITLE
libfuzzer_coverage task should verify targets include supported instrumentation early

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#540]
In the case we have a libfuzzer without detectable instrumentation, the following happens:

1. start the coverage task
2. wait for a new input (could be a *long* wait)
3. attempt to extract coverage from the input, which fails.

We should be able to inspect the application to verify it has the required coverage symbols before waiting for new inputs.

This would drastically improve the usability of informing users when their target has issues.

**Comment by bmc-msft** [comment]
To support loading libraries via `dlopen` or `LoadLibrary` within `LLVMFuzzerInitialize`, the verification step should feed in a sample input (like an empty file) and verify that the debugger instrumentation outputs coverage files.

**Comment by bmc-msft** [comment]
I believe this is addressed already with your new coverage task.

**Comment by mgreisen** [comment]
Handled in the new task.
