### ISSUE TITLE
LibFuzzer coverage task failed to synchronize coverage to container

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#542]
## Information

- Onefuzz version: 2.4.1
- OS: MicrosoftWindowsDesktop:Windows-10:20h2-pro:latest

## Provide detailed reproduction steps (if any)

Job was submitted with the following arguments:

```
onefuzz template libfuzzer basic --setup_dir <setup> --target_exe <target> --inputs <inputs> --duration 72 --notification_config <config> --reboot_after_setup -v <project> <name> <build> <pool>
```

1. Submit artifacts of job id `40eee076-df8b-4c4f-b6cd-4970625fde1b` from the internal instance. 
2. Wait ~20 minutes
3. Verify coverage files are not synchronized to container
4. Connect to host directly via SSH or RDP and confirm coverage files have been generated locally

### Expected result

Coverage files would appear in container

### Actual result

Coverage files do not appear in container

**Comment by bmc-msft** [comment]
@jagunter we fixed an issue that we believe addresses this issue, #542.
