### ISSUE TITLE
add `onefuzz containers files download_dir`

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#571]
We've made it easy to upload & download a single file, but only upload a directory of files.  We should support downloading a container similarly.

**Comment by jagunter** [comment]
In the interim, on Windows can use the following powershell script to download all the files from a container into your cwd

```
container = "some_container"
onefuzz containers files list $container | ConvertFrom-Json |% { $_.files |% { onefuzz containers files get $container $_ > $_} }
```
