### ISSUE TITLE
Job_Failed Custom Event/Telemetry

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#632]
Hi Team, 

In order to track job health, we'd like to request a Job_Failed event. This event would be fired off anytime a single task failed. Ideally it would include job_id info, as well as it's sub-task ids (and/or which task failed). 

If this is something your team believes that we can take care of ourselves, please let us know and we will reach out for guidance. 

Please reach out if there are any questions. 

Thanks!

**Comment by bmc-msft** [comment]
A [Job](https://github.com/microsoft/onefuzz/blob/main/docs/terminology.md#job) at it's core, is just an easy way to refer to a collection of tasks.  OneFuzz does not have a concept of jobs failing, only tasks.

The built-in `libfuzzer simple` template maps the set of tasks for a single libfuzzer target into a single job.  However, this mapping is not a requirement.  We have users that appear to use the `job` to indicate all of the targets for a given application (think Edge, which has hundreds of libfuzzer targets for the Edge application).

To your request, when a task fails, it generates a [task_failed](https://github.com/microsoft/onefuzz/blob/main/docs/webhook_events.md#task_failed) event, which includes the `job_id` ,`task_id`, and the full task config (which indicates the type of task).  Does this meet your needs?

**Comment by nharper285** [comment]
I believe it does, and thank you for the clarification. I think my needs will be met by just tracking failed tasks, and I can link those to individual jobs because we now include job ids. 

My only question is - does a failed task == (essentially) a failed job. Apologies if I am still misunderstanding something.

**Comment by bmc-msft** [comment]
Example, if we have a `libFuzzer` target where the coverage extraction fails, but fuzzing and crash reporting can still be successful and valuable.

**Comment by nharper285** [comment]
I see... so what task would we want to alert a failed job on? Just the fuzzing/crash reporting tasks?

**Comment by bmc-msft** [comment]
@nharper285 , based on our discussions offline, I've opened the following issues related to this discussion: #642, #643, #644, and #645.  I believe these issues will meet your underlying need.  Can you please review these issues?

**Comment by bmc-msft** [comment]
Closed per discussion
