### ISSUE TITLE
panics when using timeouts on local mode

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#737]
On occasion, I see panics from the timeout code.  Even with RUST_BACKTRACE to full, this is the most verbose error I see:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Disconnected', /home/USERNAME/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-4.0.15/src/inotify.rs:305:34
stack backtrace:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Disconnected', /home/USERNAME/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-4.0.15/src/inotify.rs:305:34
```

**Comment by ranweiler** [comment]
Upstream source of panic: https://github.com/notify-rs/notify/blob/v4.0.15/src/inotify.rs#L293-L308

**Comment by ranweiler** [comment]
@chkeita, are you actively working on this?

**Comment by ranweiler** [comment]
Note: could possibly be superseded by: #1083

**Comment by chkeita** [comment]
Closing this since i could not repro it after upgrading to [tokio 1.5.0](https://github.com/microsoft/onefuzz/pull/800)
