### ISSUE TITLE
PDB paths are not searched by PE module processor

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#777]
When we process PE modules for disassembly in `coverage::pe::process_modules()`, we _only_ try to resolve the PDB using the CV `filename` attr.

Instead, we should ideally search in the same way dbghelp API would, as seen [here](https://docs.microsoft.com/en-us/windows/win32/debug/symbol-paths#example-search-path). In particular, we must make sure that we include the directory containing the PE.

**Comment by ranweiler** [comment]
Note: this doesn't impact the custom debugger, because that uses symbol handler APIs. This issue is limited to [here](https://github.com/microsoft/onefuzz/blob/3e7b3df34f29fb376e599ed77c9d57d1c32120ce/src/agent/coverage/src/pe.rs#L242-L244).

**Comment by lzybkr** [comment]
The dbghelp API to use is [SymFindDebugInfoFileW](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-symfinddebuginfofilew).

It does require some setup (which our debugger does when asked) - namely calling [SymInitializeW](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-syminitializew) and [SymLoadModuleExW](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-symloadmoduleexw).

**Comment by lzybkr** [comment]
Ugh, yes. Not sure how I found the correct api after finding that one, but still linked to the wrong one. Sorry about that.

**Comment by lzybkr** [comment]
Note that you can pass `NULL` for the `SearchPath` and it will pick up the path set from `SymInitialize` (which we also pass `NULL` so we pick up the default.)
