### ISSUE TITLE
Permissions issue setting up OneFuzz on Azure

### ISSUE THREAD

**Issue by shambho** [microsoft/onefuzz#813]
I'm working on setting up OneFuzz on my company's Azure subscription and I'm facing permissions issue with the deployment script. I have satisfied all the prerequisites needed before running the deployment script

The [Getting Started](https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md) guide currently doesn't capture all the permissions needed to deploy OneFuzz. According to [this PR discussion](https://github.com/microsoft/onefuzz/pull/262#issuecomment-722520589), [AppRoleAssignment.ReadWrite.All](https://docs.microsoft.com/en-us/graph/permissions-reference#delegated-permissions-4) permission is required to deploy OneFuzz. My deployment script currently fails with the error, **Insufficient privileges to complete the operation**, at the Application Registration step. Here's the stack trace of the error:

```
INFO:deploy:checking if RBAC already exists
INFO:deploy:creating Application registration
Traceback (most recent call last):
  File ".\deploy.py", line 1049, in <module>
    main()
  File ".\deploy.py", line 1043, in main
    state[1](client)
  File ".\deploy.py", line 320, in setup_rbac
    app = client.applications.create(params)
  File "C:\Python38\lib\site-packages\azure\graphrbac\operations\applications_operations.py", line 86, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: Insufficient privileges to complete the operation.
```

Looks like the deployment script is trying to create a "Client App" under Azure Active Directory and currently my AD account doesn't have permissions to create a new registration. Our AD team is reluctant to add the **AppRoleAssignment.ReadWrite.All** permission as it is too permissive. Is there a least privilege approach that we can take here to satisfy the requirement for client app registration and proceed with the deployment? If you can provide additional guidance on how to deploy OneFuzz in a corporate setting where full permissions can't be assumed by the deployer, that would be great.

Let me know if you need more information from me? Thanks!

**Comment by chkeita** [comment]
Unfortunately, `AppRoleAssignment.ReadWrite.All` is already the least privileged permission required to be able [assign an App Role](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-1.0&tabs=http#permissions).
Would it be possible to have a admin deploy the application ? Or use the [Privileged Identity Management](https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-configure) to temporarily elevate your permissions in order to deploy the application.

**Comment by chkeita** [comment]
Also the script seem to be failing when creating the application registration itself so the missing permission for that operation is likely [`Application.ReadWrite.All`](https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http#permissions) which is also the least privileged permission required here.

**Comment by shambho** [comment]
@chkeita Ok, the `Application.ReadWrite.All` permission still seems to have a lot of permissions since it would still allow a principal with these permissions to create, read, update, delete not the just the client app needed for the deployment but any other app that is in the Azure AD which might not be ok with my AD team. Let me confirm this with them.

Regarding the possibility of an admin deploying the application, unfortunately that is not possible as I'm part of the Security team and would like to have the capability to deploy, update OneFuzz whenever needed since our team would be maintaining the service.

Regarding Privileged Identity Management, let me talk to my AD team about it and see if this is something they would be interested in.

In the meantime, are there any workarounds that we can take here to go ahead with the deployment? [This comment](https://github.com/microsoft/onefuzz/pull/262#issuecomment-725357073) seems to suggest that the `Application.ReadWrite.All` permission is only needed for deployment is not needed after, even for upgrades. Is that right? If so, can I have my AD team manually register the application and add me as the "Owner" of the app as described in the [Known Issues](https://github.com/microsoft/onefuzz/blob/main/docs/known-issues.md) page (2nd sub-bullet in the 5th point)? I'm assuming the "Owner" permissions here are tied to the specific app needed for OneFuzz and not all the apps in Azure AD. Can you confirm?

Also, on a side note, can you explain what is the purpose of the Client App OneFuzz is trying to create and how is it used during and after deployment in the OneFuzz service? Didn't find any documentation on this hence my question. Thanks.

**Comment by chkeita** [comment]
> This comment seems to suggest that the Application.ReadWrite.All permission is only needed for deployment is not needed after 

Yes it is true as long as the update does not modify the the application registration (which are the majority of updates). 

> can I have my AD team manually register the application and add me as the "Owner" 

Yes that is possible and having the admin call the deployment script will help for that. The deployment script will create the application registration and the admin is free to assign it to you. 
The script [does not just create the registration](https://github.com/microsoft/onefuzz/blob/8d5a7d1ed593e6f9d78eba44f24f9e4f3d62c283/src/deployment/deploy.py#L247). It also configure the roles and the backing service principal so the manual creation is not a trivial operation.

> I'm assuming the "Owner" permissions here are tied to the specific app needed for OneFuzz and not all the apps in Azure AD. Can you confirm

yes making you the owner of the application registration will only affect OneFuzz

> can you explain what is the purpose of the Client App OneFuzz is trying to create and how is it used during and after deployment in the OneFuzz service?

The client app registration is used by the cli to connect to the Onefuzz service. The deployment creates two registration. One for the service itself and the this one for the cli client.

**Comment by shambho** [comment]
Ok, thanks for the responses. I'll discuss these answers with my AD team and will get back to you.

**Comment by shambho** [comment]
@chkeita I'm still working on implementing the workaround suggested above with our AD team. In the mean time, can you answer Ryan's question [here](https://github.com/microsoft/onefuzz/pull/262#issuecomment-818845323) about delegated vs application permission for `AppRoleAssignment.ReadWrite.All`? Ryan is from my AD team and an answer to his question would help prioritize my deployment work. Thank you.

**Comment by shambho** [comment]
@chkeita Our AD team is still a bit reluctant in running the deployment script with the above permissions before reviewing the `deploy.py` code to understand what it is doing. While we work on reviewing `deploy.py` script can you please also share the steps that an admin needs to take to deploy OneFuzz manually? We would probably take this approach, if it is feasible, over asking an admin to run the deployment script. Appreciate your help. Thank you.

**Comment by chkeita** [comment]
@shambho 
The deployment script is the only supported way to register the application. We do not support the manual creation. 
You are welcome to translate the deployment code to manual steps or wait for the audit of the deployment script.

**Comment by shambho** [comment]
@chkeita Ok, thanks. I'd like to keep this issue still open until we do the deployment so that we can reach out to you with questions that may come up in the deployment process, if that is ok with you?

**Comment by shambho** [comment]
@chkeita Closing this issue as Ryan from my AD team created the app registrations manually and assigned the respective roles etc. I was able to deploy OneFuzz after that and I'm able to use OneFuzz CLI now. Ryan's other issue, #875, once addressed should help other enterprises in the future who would like to take the same route as us in manually registering the applications and setup roles rather than the AD admin running the deployment script. Thank you.
