### ISSUE TITLE
Add doc index for GH pages, fix links

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#853]
- Add an `index.md`, so our docs are rendered with a nice landing page on `microsoft.github.io/onefuzz`
- Make sure this index page highlights "must see" getting started and tutorial docs, so they don't get lost in the entire set of available docs, many of which are more references
- Update all source links so they link they are absolute links to the OneFuzz repo (and work via the rendered docs page), instead of relative links within the repo 

AB#35983

**Comment by Porges** [comment]
At least the first two bullet points have been addressed by #2095

**Comment by Porges** [comment]
Believe this is solved for now.
