### ISSUE TITLE
Files of the format ".azDownload-guid-input" are being uploaded to inputs container

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#856]
## Information

- Onefuzz version: 2.14.0
- OS: Canonical:UbuntuServer:18.04-LTS:latest

## Provide detailed reproduction steps (if any)

1. Submit job with generic supervisor task
2. `onefuzz containers files list <inputs container>`

### Expected result

Only input files generated by the fuzzer are uploaded to the inputs container

### Actual result

Files such as

```
.azDownload-12e6ac53-bf7c-864c-4254-b16917146cb6-<input-file>
```

are also uploaded to the inputs container

In the worst cases this creates a feedback loop, resulting in files like

```
.azDownload-a4f3c77f-1d1b-1b4f-49e3-206532bf66e2-.azDownload-33927fcb-efe8-214c-4fed-2d300b04f527-.azDownload-147eab04-03d9-e44d-5e3f-3bc5fc02bf01-<input-file>
```

In these cases eventually the fuzzing task will fail due to an azcopy error.

**Comment by bmc-msft** [comment]
We need to either explicitly ignore .azDownload files OR add synchronization
