### ISSUE TITLE
Scalesets may get stuck resizing

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#857]
## Information

- Onefuzz version: 2.14.0
- OS: Either Windows and Linux

## Provide detailed reproduction steps (if any)

1. `onefuzz scalesets update --size <new-size> <guid>`

### Expected result

The scaleset would eventually be resized

### Actual result

Downsizing a Linux scaleset shows it trying to resize over and over:

```
    "scalesets: scaleset resize: scaleset_id:4efb00b5-7ae0-4e0b-8b16-dbe87ec04c7c size:5",
    "scalesets: scaleset resize: scaleset_id:4efb00b5-7ae0-4e0b-8b16-dbe87ec04c7c size:5",
    "scalesets: scaleset resize: scaleset_id:4efb00b5-7ae0-4e0b-8b16-dbe87ec04c7c size:5",
```

Upsizing a Windows scaleset says an update is already in progress, but unable to find further details

```
scalesets: unable to update configs, update already in progress. scaleset_id:a2f1eb35-ac0c-47fb-9a53-065a1e7c5035",
    "scalesets: updating scaleset configs. scaleset_id:a2f1eb35-ac0c-47fb-9a53-065a1e7c5035",
    "scalesets: scaleset is unavailable. scaleset_id:a2f1eb35-ac0c-47fb-9a53-065a1e7c5035",
    "scalesets: scaleset resize: scaleset_id:a2f1eb35-ac0c-47fb-9a53-065a1e7c5035 size:5",
    "processing state update: ('[POOL_NAME_REMOVED]', UUID('a2f1eb35-ac0c-47fb-9a53-065a1e7c5035')) - resize",  
```

Neither updates appear to be making any progress after multiple hours.

**Comment by bmc-msft** [comment]
Investigating this instance, the scaleset was manually deleted outside of OneFuzz.  We don't handle resources we manage vanishing out from underneath us.
