### ISSUE TITLE
use Application Insights API-Keys instead of AAD authentication

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#863]
Currently, a user must be granted 'Reader' RBAC access in order to read application insights data - whether it be through the portal directly or through CLI commands like onefuzz debug logs query'. 

With the _alternate tenant_ migration underway, it is necessary to move away from this approach, as most users will not have _alternate tenant_ credentials and can therefore not be granted access (you cannot grant _primary tenant_ creds access to _alternate tenant_ resources).

**Comment by stishkin** [comment]
This is captured in #1428
