### ISSUE TITLE
App Roles for the App Registration should be documented

### ISSUE THREAD

**Issue by ryanspletzer** [microsoft/onefuzz#875]
I had to dig through the python deployment script in order to understand the app roles that needed to be configured on the app registration.

https://github.com/microsoft/onefuzz/blob/54d49a973e4007b3db2ff0d134d368c648183524/src/deployment/deploy.py#L272-L289

## Provide a description of requested docs changes

This should more clearly be delineated in markdown documentation in the event that someone is trying to create the app registration by hand. In most secure enterprises, people do not have standing access to create apps / service principals in Azure AD and there is typically a process for getting one created. In this event, in would be helpful to have this documented to save people time from trying to discern all the things the python deployment script is doing.

@shambho 
The deployment script is the only supported way to register the application. We do not support the manual creation. 
You are welcome to translate the deployment code to manual steps or wait for the audit of the deployment script.

_Originally posted by @chkeita in https://github.com/microsoft/onefuzz/issues/813#issuecomment-827229205_

A few lines of documentation on how to set up the app registration is a reasonable ask here.

**Comment by chkeita** [comment]
That is good suggestion. We will add description of the azure entities created by the deployment script in the docs.

**Comment by chkeita** [comment]
docs [updated](https://github.com/microsoft/onefuzz/blob/2.17.0/docs/AADEntitites.md)

**Comment by ryanspletzer** [comment]
@chkeita thank you so much!
