### ISSUE TITLE
Write `target_exe` in configs as `{setup_dir}`-relative

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#924]
Right now, the service [prepends](https://github.com/microsoft/onefuzz/blob/eaf770fa22ab9069f5b8a82f9b0fdf99ca47009f/src/api-service/__app__/onefuzzlib/tasks/config.py#L278) `target_exe` values with `setup/` when generating task configs.

Instead, we should prepend the template placeholder `{setup_dir}`, which tasks should expand at runtime. 

AB#35977

**Comment by ranweiler** [comment]
When we do this, we need to make sure `coverage_filter` is relativized and updated in the same way.

**Comment by Porges** [comment]
This was done in #2405.
