### ISSUE TITLE
Scaleset resize request not applied

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#957]
## Information

- Onefuzz version: 2.18
- OS: Windows latest

## Provide detailed reproduction steps (if any)

1. Update scaleset size
2. Observe state change to `resizing` and new size being applied

For example see scaleset `1339d1c1-5d28-4481-8de0-d25eaec5a188` on prod01 instance.

### Expected result

Scaleset to get additional hosts or the update request to fail. Suspect there may be a resource limit being hit as this doesn't always occur, but it's not obvious what. Checked logs and appears to be continually attempting to resize.

### Actual result

Scaleset never gets additional hosts

**Comment by jagunter** [comment]
This appears to have been due to hitting a core quota limit. Once that was increased the resize was applied successfully without any additional user interaction.

**Comment by bmc-msft** [comment]
As we discussed offline, we're hitting an unhandled exception at the python SDK layer, which is why it was hard for you to debug it.

We need to address the exception to make it easier to debug these moving forwards.
