### ISSUE TITLE
handle quota issues during scaleset resize

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#98]
## Information

- Onefuzz version: 1.0.0
- OS: NA

## Provide detailed reproduction steps (if any)

1. Create scaleset
2. Let stablize
3. `onefuzz scaleset update $ID --size 99999`

### Expected result

Resize attempt is rejected

### Actual result

Eventually an exception about quotas is generated in the service.   

AB#39994767

**Comment by bmc-msft** [comment]
It's straight forwards how to deal with quota issues when creating scalesets.  We fail the scaleset creation, and give the Azure error to the user as scaleset.error.  

When we're resizing scalesets, this would potentially stop work that is already running on the scaleset.

**Comment by mgreisen** [comment]
We autoscale now and get quota manually now.
