### ISSUE TITLE
OneFuzz CLI Role Assignment Infrastructure

### ISSUE THREAD

**Issue by nharper285** [microsoft/onefuzz#998]
The CoSTR team is working with the OneFuzz team to build out the infrastructure to restrict user/admin CLI actions. Specifically, we are hoping to build out a process for specifying actions that can only be done by the service engineering team (CoSTR). 

(Created for tracking purposes.)

**Comment by chkeita** [comment]
The service will need the permission to check [group ](https://docs.microsoft.com/en-us/graph/api/directoryobject-checkmembergroups?view=graph-rest-1.0&tabs=http#permissions) or role membership to enforce these rules. 
At the moment these permissions require admin approval.
